<<<

:linkattrs:

== What you will need

- JDK/JRE 8
- link:https://maven.apache.org/download.cgi[Apache Maven, window="_blank"]
- link:https://github.com/steveloughran/winutils/tree/master/hadoop-2.8.3/[Apache Hadoop, window="_blank"] 

=== Setting up the Installer

In order to use some of the feature required for ingesting and analyzation, Hadoop will be needed. Follow the this link link:https://github.com/steveloughran/winutils/tree/master/hadoop-2.8.3/[here, window="_blank"]. The same must be done for Apache Maven which can be downloaded link:https://maven.apache.org/download.cgi[here, window="_blank"]. You must create a PATH system variable to the Hadoop and Apache Maven bin.

After creating the PATHs for the tools you can begin the installation of GeoWave onto your machine. The installer has step by step instructions on how to properly install the software.

=== Demo Links

- link:walkthrough-vector.html[Vector Demo, window="_blank"]
- link:walkthrough-raster.html[Raster Demo, window="_blank"]
- link:integrate-geoserver.html[GeoServer Integration, window="_blank"]
- link:interact-cluster.html[Interacting with the cluster, window="_blank"]


