[[toolsframework]]
<<<
== Tools Framework
A plugin framework (using Service Provider Interface (SPI) based injection) is provided with several input formats and utilities supported out of the box.

First we'll show how to build and use the built in formats, and after that describe how to create a new plugin.

=== Building

First build the main project after specifying the dependency versions you'd like to build against.

[source, bash]
----
export BUILD_ARGS="-Daccumulo.version=1.6.0-cdh5.1.4 -Dhadoop.version=2.6.0-cdh5.4.0 -Dgeotools.version=14.2 -Dgeoserver.version=2.8.2 -Dvendor.version=cdh5 -Daccumulo.api=1.6 -P cloudera" <1>
git clone https://github.com/ngageoint/geowave.git <2>
cd geowave
mvn install $BUILD_ARGS <3>
----
<1> Examples of current build args can be seen in the top level .travis.yml file in the env/matrix section
<2> If you don't need the complete history and want to speed up the clone you can limit the depth of your checkout with --depth NUM_COMMITS
<3> You can speed up the build by skipping tests by adding -Dfindbugs.skip=true -DskipFormat=true -DskipITs=true -DskipTests=true

Now we can build the cli tools framework

[source, bash]
----
mvn package -P geowave-tools-singlejar $BUILD_ARGS
----

The geowave tools jar is now packaged in deploy/target. When packaged for installation there will be a wrapper script named geowave
that will be installed in $PATH. In a development environment where this script has not been installed you could create a directory
containing the tools jar and any needed plugin jars and use with something like the following command ```java -cp "$DIR/* <operation> <options>```
