[[ingest-framework]]
=== Framework

A plugin framework (using SPI based injection) is provided, and several methods are supported out of the box.
The plugin framework is created in geowave-ingest, and the supported types are in geowave-types.

First we will show how to build and use the built in types, and after that describe how to create a new plugin.

==== Building ingest framework

This assumes you have already built the main project, if not first do that

[NOTE]
You should either edit the geowave/pom.xml file for the correct Accumulo, Hadoop, GeoTools, and GeoServer versions,
or supply command line parameters to override them.

[source, bash]
----
$ git clone git@github.com:ngageoint/geowave.git
$ cd geowave
$ mvn clean install
----

now we can build the ingest framework with included types

[source, bash]
----
$ cd geowave-types
$ mvn package -Pingest-singlejar
----

The ingest file is now packaged in target. When packaged for installation there will be a wrapper script named geowave-ingest
that will be installed in $PATH. In a development environment were this script has not been installed you can use the
artifact directly with the command ```java -jar geowave-types-VERSION-ingest-tool.jar <operation> <options>```

=== Cmd: geowave-ingest

include::manpages/geowave-ingest.txt[]

=== Operation: -clear

include::manpages/geowave-ingest-clear.txt[]

=== Operation: -hdfsingest

include::manpages/geowave-ingest-hdfsingest.txt[]

=== Operation: -hdfsstage

include::manpages/geowave-ingest-hdfsstage.txt[]

=== Operation: -localingest

include::manpages/geowave-ingest-localingest.txt[]

=== Operation: -poststage

include::manpages/geowave-ingest-poststage.txt[]


==== Ingesting all the things

We can ingest any data type that has been listed as an ingest plugin. Let's start out with the GeoTools datastore; this
wraps a bunch of GeoTools supported formats. We will use the shapefile capability for our example here.

==== Something recognizable

The naturalearthdata side has a few shapefile we can use use. On the page
http://www.naturalearthdata.com/downloads/50m-cultural-vectors/[50m Cultural Vectors]

Let's download the Admin 0 - Countries shapefile:
http://naciscdn.org/naturalearth/50m/cultural/ne_50m_admin_0_countries.zip[ne_50m_admin_0_countries.zip]

Okay, let's ingest this. I'll take some liberty with the file locations,
but the process should be obvious

[source, bash]
----
$ mkdir ingest
$ mv ne_50m_admin_0_countries.zip ingest/
$ cd ingest
$ unzip ne_50m_admin_0_countries.zip
$ rm ne_50m_admin_0_countries.zip
$ cd ..
$ geowave-ingest -localingest -b ./ingest -i ACCUMULO_INSTANCE_NAME -n geowave.50m_admin_0_countries -t geotools-vector -u USERNAME -p PASSWORD -z zoo-1:2181
----
