[[ingest-example]]
=== Ingest Example

GeoWave can ingest any data type that has been listed as an ingest plugin. Let's start out with the GeoTools datastore; this
wraps a bunch of GeoTools supported formats. This includes all file-based datastores supported within GeoTools.
We will use the shapefile capability for our example here.

==== Something recognizable

The naturalearthdata side has a few shapefile we can use use. On the page
http://www.naturalearthdata.com/downloads/50m-cultural-vectors/[50m Cultural Vectors]

Let's download the Admin 0 - Countries shapefile:
http://naciscdn.org/naturalearth/50m/cultural/ne_50m_admin_0_countries.zip[ne_50m_admin_0_countries.zip]

[source, bash]
----
$ mkdir ingest
$ mv ne_50m_admin_0_countries.zip ingest/
$ cd ingest
$ unzip ne_50m_admin_0_countries.zip
$ rm ne_50m_admin_0_countries.zip
$ cd ..
$ geowave config addstore -t accumulo mystore \ <1>
      --gwNamespace geowave.50m_admin_0_countries \ <2>
      --zookeeper ZOOKEEPER_HOSTNAME:2181 \
      --instance ACCUMULO_INSTANCE_NAME \
      --user USERNAME \
      --password PASSWORD
$ geowave config addindex -t spatial myindex \ <3>
      --partitionStrategy round_robin \
	  --numPartitions NUM_PARTITIONS \ <4>
$ geowave ingest localtogw ./ingest mystore myindex \ <5>
	  -f geotools-vector \ <6>

----
<1> This will create a re-usable named configuration `mystore` that can be referenced as a store by other commandline operations such as ingest
<2> We preface the table name with the Accumulo namespace we configured earlier in the Accumulo configuration section followed by a dot (NAMESPACE.TABLE_NAME)
<3> This will create a re-usable named configuration `myindex` that can be referenced as an index by other commandline operations such as ingest
<4> The index is spatial and pre-split based on the number of partitions you may desire - this is an optional parameter but an example of customization you may choose on index configuration, in this case data is randomized into different splits which can help avoid hotspotting to a single node/core
<5> Notice the ingest command uses the named configurations `mystore` and `myindex`
<6> Explicitly set the ingest formats by name (or multiple comma-delimited formats), if not set all available ingest formats will be used


After running the ingest command you should see the various index tables in Accumulo
