[[tools-framework]]
== Tools Framework

A plugin framework (using SPI based injection) is provided with several input formats and utilities supported out of the box.

First we'll show how to build and use the built in formats, and after that describe how to create a new plugin.

=== Building

First build the main project after specifynig the dependency versions you'd like to build against.

[source, bash]
----
export BUILD_ARGS="-Daccumulo.version=1.6.0-cdh5.1.4 -Dhadoop.version=2.6.0-cdh5.4.0 -Dgeotools.version=13.0 -Dgeoserver.version=2.7.0 -Dvendor.version=cdh5 -P cloudera" <1>
git clone https://github.com/ngageoint/geowave.git <2>
cd geowave
mvn install $BUILD_ARGS <3>
----
<1> Examples of current build args can be seen in the top level .travis.yml file in the env/matrix section
<2> If you don't need the complete history and want to speed up the clone you can limit the depth of your checkout with --depth NUM_COMMITS
<3> You can speed up the build by skipping tests by adding -Dfindbugs.skip=true -DskipFormat=true -DskipITs=true -DskipTests=true

Now we can build the cli tools framework

[source, bash]
----
mvn package -P geowave-tools-singlejar $BUILD_ARGS
----

The geowave tools jar is now packaged in deploy/target. When packaged for installation there will be a wrapper script named geowave
that will be installed in $PATH. In a development environment where this script has not been installed you could create a directory
containing the tools jar and any needed plugin jars and use with something like the following command ```java -cp "$DIR/* <operation> <options>```

=== geowave -clear

include::manpages/geowave-clear.txt[]

=== geowave -hdfsingest

include::manpages/geowave-hdfsingest.txt[]

=== geowave -hdfsstage

include::manpages/geowave-hdfsstage.txt[]

=== geowave -kafkastage

include::manpages/geowave-kafkastage.txt[]

=== geowave -localingest

include::manpages/geowave-localingest.txt[]

=== geowave -poststage

include::manpages/geowave-poststage.txt[]

=== geowave -stats

include::manpages/geowave-stats.txt[]

=== geowave -statsdump

include::manpages/geowave-statsdump.txt[]

=== Ingest Example

We can ingest any data type that has been listed as an ingest plugin. Let's start out with the GeoTools datastore; this
wraps a bunch of GeoTools supported formats. We will use the shapefile capability for our example here.

==== Something recognizable

The naturalearthdata side has a few shapefile we can use use. On the page
http://www.naturalearthdata.com/downloads/50m-cultural-vectors/[50m Cultural Vectors]

Let's download the Admin 0 - Countries shapefile:
http://naciscdn.org/naturalearth/50m/cultural/ne_50m_admin_0_countries.zip[ne_50m_admin_0_countries.zip]

[source, bash]
----
$ mkdir ingest
$ mv ne_50m_admin_0_countries.zip ingest/
$ cd ingest
$ unzip ne_50m_admin_0_countries.zip
$ rm ne_50m_admin_0_countries.zip
$ cd ..
$ geowave -localingest \
      -b ./ingest \
      -i ACCUMULO_INSTANCE_NAME \
      -n geowave.50m_admin_0_countries \ <1>
      -f geotools-vector \ <2>
      -u USERNAME \
      -p PASSWORD \
      -z ZOOKEEPER_HOST_NAME:2181
----
<1> We preface the table name with the Accumulo namespace we configured earlier in the Accumulo configuration section followed by a dot (NAMESPACE.TABLE_NAME)
<2> Explicitly set the ingest formats by name (or multiple comma-delimited formats), if not set all available ingest formats will be used

After running the ingest command you should see the various index tables in Accumulo
