[third-party]
<<<
== Third Party

=== GeoServer

Geowave supports both raster images and vector data exposed through Geoserver.

==== WFS-T

Extending Geotools, Geowave supports WFS-T for vector data. After following the deployment steps, Geowave appears as a
data store type called 'GeoWave Datastore'.

On the Geowave data store creation tab, the system prompts for the following properties.

[frame="topbot",options="header"]
|======================
| Name | Description | Constraints
| ZookeeperServers | Comma-separated list of Zookeeper host and port.| Host and port are separated by a colon (host:port).
| InstanceName | The Accumulo tablet server's instance name. | The name matches the one configured in Zookeeper.
| UserName | The Accumulo user name. | The user should have administrative privileges to add and remove authorized visibility constraints.
| Password | Accumulo user's password. |
| Namespace | The table namespace associated with this Accumlo data store |
| Lock Management | Select one from a list of lock managers. | Zookeeper is required with a multiple Geoserver architecture.
| Authorization Management Provider | Select from a list of providers. |
| Authorization Data URL | The URL for an external supporting service or configuration file. | The interpretation of the URL depends on the selected provider.
| Transaction Buffer Size | The maximum number of newly inserted features per transaction buffered in memory prior to transaction completion.  | Considerations include system memory, size of typical transactions, the expected number of simultaneous transactions and the average size of a new feature.  
|======================

===== Transactions

Transactions are initiated through a Transaction operation, containing inserts, updates and deletes to features.
WFS-T supports feature locks across multiple requests by using a lock request followed by subsequent 
use of a provided lock ID. The Geowave implementation supports
transaction isolation. Consistency during a commit is not fully supported. Thus, a failure during a commit of a
transaction may leave the affected data in an intermediary state--some deletions, updates or insertions may not be
processed. The client application must implement its on compensation logic upon receiving a commit-time error response.
As expected with Accumulo, operations on a single feature instances are atomic.

Inserted features are buffered prior to commit.  The features are bulk fed to the data store 
when the buffer size is exceeded and when the transaction is committed.  In support of atomicity and isolation,
flushed features, prior to commit, are marked in a transient state, only visible to the controlling
transaction.   Upon commit, these features are 'unmarked'. The overhead incurred by this operation is avoided
by increasing the buffer size to avoid pre-commit flushes.
  
===== Lock Management

Lock management supports life-limited locks on feature instances. There are only two supported lock managers: in memory
and Zookeeper. Memory is suitable for single Geoserver instance installations.

===== Index Selection

Data written through WFS-T is indexed within a single index.  The adapter inspects existing indices, finding one that matches
the data requirements.  A geo-temporal index is chosen for features with temporal attributes.  The adapter creates a geo-spatial index
upon failure of finding a suitable index.  Geo-temporal index is not created, regardless of the existence of temporal attributes.  Currently, 
geo-temporal indices lead to poor performance for queries requesting vectors over large spans of time. 

==== Authorization Management

Authorization Management provides the set of credentials compared against the security labels attached to each cell.
Authorization Management determines the set of authorizations associated with each WFS-T request. The available
Authorization Management strategies are registered through the Server Provider model, within the file
`META-INF/services/mil.nga.giat.geowave.vector.auth.AuthorizationFactorySPI`.

The provided implementations include the following:
. Empty - Each request is processed without additional authorization.
. JSON - The requester user name, extracted from the Security Context, is used as a key to find the user's set of
authorizations from a JSON file. The location of the JSON file is determined by the associated _Authorization Data URL_
(e.g. file://opt/config/auth.json). An example of the contents of the JSON file is given below.

[source, json]
----
    {
      "authorizationSet": {
         "fred" : ["1","2","3"],
         "barney" : ["a"]
      }
    }
----

Fred has three authorization labels. Barney has one.

==== Visibility Management

Visibility constraints, applied to feature instances during insertions, are ultimately determined a
`mil.nga.giat.geowave.store.data.field.FieldWriter`, of which there are writers for each supported data type in
Geoserver. By default, the set visibility expression attached to each feature property is empty. Visibility Management
supports selection of a strategy by wrapping each writer to provide visibility. This alleviates the need to extend the
type specific FieldWriters.

The visibility management strategy is registered through the Java Server Provider model, within in the file
`META-INF/services/mil.nga.giat.geowave.vector.plugin.visibility.ColumnVisibilityManagement`. The only provided
implementation is the `JsonDefinitionColumnVisibilityManagement`. The implementation expects an property within each
feature instance to contain a JSON string describing how to set the visibility for each property of the feature
instance. This approach allows each instance to determine its own visibility criteria.

Each name/value pair within the JSON structure defines the visibility for the associated feature property with the same
name. In the following example, the _geometry_ property is given a visibility `S`; the eventName is given a visibility `TS`.

[source, json]
----
{ "geometry" : "S", "eventName": "TS" }
----

JSON attributes can be regular expressions, matching more than one feature property name. In the example, all properties
except for those that start with 'geo' have visibility `TS`.

[source, json]
----
{ "geo.*" : "S", ".*" : "TS" }
----

The order of the name/value pairs must be considered if one rule is more general than another, as shown in the example.
The rule `.*` matches all properties. The more specific rule `geo.*` must be ordered first.

The system extracts the JSON visibility string from a feature instance property named `GEOWAVE_VISIBILITY`. Selection
of an alternate property is achieved by setting the associated attribute descriptor 'visibility' to the boolean value TRUE.

==== Statistics

The adapter captures statistics for each numeric, temporal and geo-spatial attribute.  Statistics are used to constrain queries and 
answer inquiries by GeoServer for data ranges, as required for map requests and calibration of zoom levels in Open Layers.
