[[install-from-rpm]]
<<<
== Installation from RPM

=== Overview

There is a public http://s3.amazonaws.com/geowave-rpms/index.html[GeoWave RPM Repo] available with the following packages.
As you'll need to coordinate a restart of Accumulo to pick up changes to the GeoWave iterator classes the repos default to
be disabled so you can keep auto updates enabled. When ready to do an update simply add `--enablerepo=geowave` to your
command.

=== Examples

[source, bash]
----
# Use GeoWave repo RPM to configure a host and search for GeoWave RPMs to install
rpm -Uvh http://s3.amazonaws.com/geowave-rpms/release/noarch/geowave-repo-dev-1.0-3.noarch.rpm
yum --enablerepo=geowave search geowave

# Install GeoWave Accumulo iterator on a host (probably a namenode)
yum --enablerepo=geowave install geowave-cdh5-accumulo

# Update
yum --enablerepo=geowave install geowave-*
Restart Accumulo service
----

.GeoWave RPMs
[cols="2*", options="header"]
|===
|Name
|Description

|geowave-cdh5-accumulo
|Accumulo Components

|geowave-cdh5-core
|Core (home directory and geowave user)

|geowave-cdh5-docs
|Documentation (HTML, PDF and man pages)

|geowave-cdh5-ingest
|Ingest Tool

|geowave-cdh5-jetty
|GeoServer Components

|geowave-cdh5-puppet
|Puppet Scripts

|geowave-cdh5-single-host
|All GeoWave Components

|geowave-repo
|GeoWave RPM Repo config file

|geowave-repo-dev
|GeoWave Development RPM Repo config file

|===