[[install-from-rpm]]
<<<
== Installation from RPM

=== Overview

There is a public http://ngageoint.github.io/geowave/packages.html[GeoWave RPM Repo] available with the following packages.
As you'll need to coordinate a restart of Accumulo to pick up changes to the GeoWave iterator classes the repos default to
be disabled so you can keep auto updates enabled. When ready to do an update simply add `--enablerepo=geowave` to your
command. The packages are built for a number of different hadoop distributions (Cloudera, Hortonworks and Apache) the RPMs
have the vendor name embedded as the second portion of the rpm name (geowave-apache-accumulo, geowave-hdp2-accumulo or geowave-cdh5-accumulo)

=== Examples

[source, bash]
----
# Use GeoWave repo RPM to configure a host and search for GeoWave RPMs to install
rpm -Uvh http://s3.amazonaws.com/geowave-rpms/release/noarch/geowave-repo-1.0-3.noarch.rpm
yum --enablerepo=geowave search geowave

# Install GeoWave Accumulo iterator on a host (probably a namenode)
yum --enablerepo=geowave install geowave-cdh5-accumulo

# Update
yum --enablerepo=geowave install geowave-*
Restart Accumulo service
----

.GeoWave RPMs
[cols="2*", options="header"]
|===
|Name
|Description

|geowave-*-accumulo
|Accumulo Components

|geowave-*-core
|Core (home directory and geowave user)

|geowave-*-docs
|Documentation (HTML, PDF and man pages)

|geowave-*-ingest
|Ingest Tool

|geowave-*-jetty
|GeoServer components installed into /usr/local/geowave/geoserver and available at http://FQDN:8080/geoserver

|geowave-*-puppet
|Puppet Scripts

|geowave-*-single-host
|All GeoWave Components installed on a single host (sometimes useful for development)

|geowave-repo
|GeoWave RPM Repo config file

|geowave-repo-dev
|GeoWave Development RPM Repo config file

|===


=== RPM Installation Notes

* geowwave-cdh5-accumulo: This RPM will install the GeoWave Accumulo iterator into the local file system and then upload
it into HDFS using the `hadoop fs -put` command. This means of deployment requires that the RPM is installed on a node that
has the correct binaries and configuration in place to push files to HDFS, like your namenode.
* With the exception of the Accumulo RPM mentioned above you can install the rest of the RPMs all on a single node or
a mix of nodes depending on your cluster configuration. All GeoWave files get installed into the `/usr/local/geowave/' directory
