[[install-from-source]]
<<<
== Installation from Source

=== GeoServer

==== GeoServer Versions

GeoWave has to be built against specific versions of GeoWave and GeoTools. To see the currently supported versions look at
the build matrix section of the .travis.yml file in the root directory of the project. All of the examples below use the variable
$BUILD_ARGS to represent your choice of all the dependency versions.

Example build args:

[source, bash]
----
export BUILD_ARGS="-Daccumulo.version=1.6.0 -Dhadoop.version=2.5.0-cdh5.3.0 -Dgeotools.version=13.0 -Dgeoserver.version=2.7.0 -Dvender.version=cdh5 -P cloudera"
----

==== GeoServer Install

First we need to build the GeoServer plugin - from the GeoWave root directory:

[source, bash]
----
mvn package -P geotools-container-singlejar $BUILD_ARGS
----

let's assume you have GeoServer deployed in a Tomcat container in
/opt/tomcat

[source, bash]
----
cp deploy/target/*-geoserver-singlejar.jar /opt/tomcat/webapps/geoserver/WEB-INF/lib/
----

and re-start Tomcat

=== Accumulo

==== Accumulo Versions

GeoWave has been tested and works against accumulo 1.5.0, 1.5.1, 1.6.0 and 1.6.1 Ensure you've set the desired
version in the BUILD_ARGS environment variable

==== Accumulo Install

[source, bash]
----
mvn package -P accumulo-container-singlejar $BUILD_ARGS
----
