[[building]]
<<<
== Building

GeoWave will shortly be available in maven central (for tagged releases), but until then - or to get the latest
features - building GeoWave from source is the best bet.

=== Application Dependencies

This _ultra_ quickstart assumes you have installed and configured:

* http://git-scm.com/[Git]
* http://www.oracle.com/technetwork/java/javase/downloads/index.html[Java JDK] (>= 1.7). The OracleJDK is the most thoroughly tested, but there
are no known issues with OpenJDK.
* https://maven.apache.org/[Maven] >= 3.2.1
* http://geoserver.org/[GeoServer] instance >= 2.5.2 (due to: http://jira.codehaus.org/browse/GEOT-4587[GEOT-4587])
* http://projects.apache.org/projects/accumulo.html[Apache Accumulo] version 1.5 or greater is required. 1.5.0, 1.5.1, and 1.6.0 have all
been tested.
* http://hadoop.apache.org/[Apache Hadoop] versions 1.x and 2.x _should_ all work. The software has specifically been run on:
* http://cloudera.com/content/cloudera/en/home.html[Cloudera] CDH4 and CDH5 (MR1)
* http://hortonworks.com/hdp/[Hortonworks Data Platform] 2.1. +
* MapReduce 1 with the new API (org.apache.hadoop.mapreduce.*) is used. Testing is underway against YARN / MR2 and seems to be positive, but
well, it's still underway.
* http://download.java.net/media/jai/builds/release/1_1_3/[Java Advanced Imaging] and http://download.java.net/media/jai-imageio/builds/release/1.1/[Java
Image I/O] are also both required to be installed on the GeoServer instance(s) _as well_ as on the Accumulo nodes. The Accumulo support is
only required for certain functions (distributed rendering) - so this may be skipped in some cases.

=== Maven dependencies

Required repositories not in Maven Central have been added to the parent POM. Specifically the cloudera and opengeo repos.

=== Build Process

Checkout geowave, set your preferred dependencies as build arguments and then run maven install.

[source, bash]
----
export BUILD_ARGS="-Daccumulo.version=1.6.0-cdh5.1.4 -Dhadoop.version=2.6.0-cdh5.4.0 -Dgeotools.version=13.0 -Dgeoserver.version=2.7.0 -Dvendor.version=cdh5 -P cloudera" <1>
git clone https://github.com/ngageoint/geowave.git <2>
cd geowave
mvn install $BUILD_ARGS <3>
----
<1> Examples of current build args can be seen in the top level .travis.yml file in the env/matrix section
<2> If you don't need the complete history and want to speed up the clone you can limit the depth of your checkout with --depth NUM_COMMITS
<3> You can speed up the build by skipping tests by adding -Dfindbugs.skip=true -DskipFormat=true -DskipITs=true -DskipTests=true

[NOTE]
====
Integration Tests: Windows

Integration tests are currently not working on Windows out of the box. If you install cygwin and set the environmental variable CYGPATH to the
location of the cygpath binary provided by cygwin then is should work. Eclipse and Avro generated files
====
