[[building]]
<<<
== Building

GeoWave will shortly be available in maven central (for tagged releases), but until then - or to get the latest
features - building GeoWave from source is the best bet.

=== Application Dependencies

This _ultra_ quickstart assumes you have installed and configured:

* http://git-scm.com/[Git]
* http://www.oracle.com/technetwork/java/javase/downloads/index.html[Java JDK] (>= 1.7). The OracleJDK is the most thoroughly tested, but there
are no known issues with OpenJDK.
* http://geoserver.org/[GeoServer] instance >= 2.5.2 (due to: http://jira.codehaus.org/browse/GEOT-4587[GEOT-4587])
* http://projects.apache.org/projects/accumulo.html[Apache Accumulo] version 1.5 or greater is required. 1.5.0, 1.5.1, and 1.6.0 have all
been tested.
* http://hadoop.apache.org/[Apache Hadoop] versions 1.x and 2.x _should_ all work. The software has specifically been run on:
* http://cloudera.com/content/cloudera/en/home.html[Cloudera] CDH4 and CDH5 (MR1)
* http://hortonworks.com/hdp/[Hortonworks Data Platform] 2.1. +
* MapReduce 1 with the new API (org.apache.hadoop.mapreduce.*) is used. Testing is underway against YARN / MR2 and seems to be positive, but
well, it's still underway.
* http://download.java.net/media/jai/builds/release/1_1_3/[Java Advanced Imaging] and http://download.java.net/media/jai-imageio/builds/release/1.1/[Java
Image I/O] are also both required to be installed on the GeoServer instance(s) _as well_ as on the Accumulo nodes. The Accumulo support is
only required for certain functions (distributed rendering) - so this may be skipped in some cases.

=== Maven dependencies

Required repositories not in Maven Central have been added to the parent POM. Specifically the cloudera and opengeo repos.

=== Build Process

Checkout geowave, and run a maven install.

[source, bash]
------------------------------------------------
$ git clone git@github.com:ngageoint/geowave.git
$ cd geowave && mvn install 
------------------------------------------------

[NOTE]
====
Integration Tests: Windows

Integration tests are currently not working on Windows out of the box. If you install cygwin and set the environmental variable CYGPATH to the
location of the cygpath binary provided by cygwin then is should work. Eclipse and Avro generated files
====

=== Avro
There are Avro generated sources in the geowave-types project and geowave-ingest.  They can be created by running "mvn generate-sources" (and are compiled as part of the standard maven lifecycle normally).  Unfortunately, I can't seem to make eclipse run this portion of the lifecycle on import with the M2E plugin.   On first import simply type "mvn generate-sources" at the command line and then refresh your eclipse project.
