[[PDAL]]
<<<
== PDAL

The Point Data Abstraction Library http://www.pdal.io/index.html[PDAL] is a BSD licensed library for translating
and manipulating point cloud data of various formats.  GeoWave is supported as a plugin for PDAL for both reading
and writing data to Accumulo.

=== GeoWave Plugin Setup


==== Prepackaged RPM Setup

Coming Soon...

For a quick and easy setup, you can grab one of our prepackaged RPMs.


=== Manual Setup

If you want to integrate with the latest version of GeoWave or perhaps a specific branch, you can build the Jace bindings yourself.


==== Step 1 - Checkout PDAL and GeoWave

First, we need to clone PDAL and GeoWave.

[source, bash]
----
$ git clone git@github.com:PDAL/PDAL.git
$ git clone git@github.com:ngageoint/geowave.git
----

==== Step 2 - Build GeoWave

In order to generate the Jace bindings for PDAL, we need to build GeoWave using Maven.

We will also specify two Maven profiles; one which specifies our target platform, and another to specify that we
are building PDAL Jace proxies.

Additionally, we need specify the path to the PDAL project.

[source, bash]
----
$ cd geowave
$ mvn clean package -pl geowave-deploy -am -P generate-pdal-proxies,linux-amd64-gcc-debug -Dpdal.directory=/path/to/PDAL -Dmaven.test.skip=true
----

Refer to the table below to select the platform most applicable to your needs.

[cols="4*", options="header"]
|===
|Profile
|Generator
|Config
|Architecture

|windows-amd64-vc11-debug
|Visual Studio 11 Win64
|Debug-x64
|amd64

|windows-amd64-vc11-release
|Visual Studio 11 Win64
|Release-x64
|amd64

|linux-amd64-vc11-debug
|Unix Makefiles
|
|amd64

|linux-amd64-vc11-release
|Unix Makefiles
|
|amd64
|===

==== Step 3 - Configure cmake for PDAL

Once Maven has finished, you will have generated all of the required artifacts for running GeoWave as a PDAL plugin.  The artifacts can be found in the target folder within geowave-deploy.

Now that the GeoWave plugin artifacts have been generated, we need to use cmake to configure PDAL to build with our plugin.

To configure PDAL to run with GeoWave, there are a few cmake options which need to be configured.  While some of the options (namely the JAVA options) may configure automatically, some will need to be set manually.  Refer to the table below to get an idea for how these options would be configured using GeoWave v0.8.3 on Ubuntu 14.04 LTS.

[cols="3*", options="header"]
|===
|Option
|Value
|Automatically Configured?

|BUILD_PLUGIN_GEOWAVE
|ON
|

|GEOWAVE_RUNTIME_JAR
|/path/to/geowave/geowave-deploy/target/geowave-deploy-0.8.3-jace.jar
|

|JACE_INCLUDE_DIR
|/path/to/geowave/geowave-deploy/target/dependency/jace/include
|

|JACE_LIBRARY
|/path/to/geowave/geowave-deploy/target/dependency/jace/libjace.so
|

|JACE_RUNTIME_JAR
|/path/to/geowave/geowave-deploy/target/dependency/jace-core-runtime-1.2.22.jar
|

|JAVA_AWT_INCLUDE_PATH
|/usr/local/java/jdk1.7.0_21/include
|X

|JAVA_AWT_LIBRARY
|/usr/local/java/jdk1.7.0_21/jre/lib/amd64/libjawt.so
|X

|JAVA_INCLUDE_PATH
|/usr/local/java/jdk1.7.0_21/include
|X

|JAVA_INCLUDE_PATH2
|/usr/local/java/jdk1.7.0_21/include/linux
|X

|JAVA_JVM_LIBRARY
|/usr/local/java/jdk1.7.0_21/jre/lib/amd64/server/libjvm.so
|X
|===


==== Step 4 - Build PDAL

Once cmake is configured, you can proceed with your normal PDAL build process.

Last, but not least, you should ensure that the libraries specified above are available either via PATH or LD_LIBRARY_PATH.

Within the PDAL documentation, you can see examples of how GeoWave can be used as both a
http://www.pdal.io/stages/readers.geowave.html[reader] and http://www.pdal.io/stages/writers.geowave.html[writer].