[[jace-jni-proxies]]
<<<
== Jace JNI Proxies

Using Jace, we are able to create JNI proxy classes for GeoWave which can be used in C/C++ applications.  

Boost is required when using the Jace bindings.  

=== Prepackaged Source and Binaries

There is a public http://ngageoint.github.io/geowave/packages.html[GeoWave RPM Repo] where you can download a tarball for the GeoWave Jace bindings for your desired platform.  If your platform is not available, there is a source tarball which can be used in conjunction with CMake to build the GeoWave Jace bindings for your desired platform.  

=== Generate Proxies and Build from Source

If you want, you can generate and build the Jace proxies yourself.  

==== Step 1 - Checkout Jace and GeoWave

First, we need to clone Jace and GeoWave.

[source, bash]
----
$ git clone git@github.com:jwomeara/jace.git
$ git clone git@github.com:ngageoint/geowave.git
----

Note: We are using a non-standard Jace implementation.

==== Step 2 - Install Jace

First, we need to install Jace v1.3.0.  This is the software which is used to generate the C++ proxy classes.

[source, bash]
----
$ cd jace
$ git checkout tags/v1.3.0
$ mvn clean install -Dsources
----

==== Step 3 - Build GeoWave

Here, we will specify two Maven profiles; one which specifies that we are building jace proxies, and another to specify our target platform.

[source, bash]
----
$ cd geowave
$ mvn clean package -pl deploy -am -P generate-jace-proxies,linux-amd64-gcc-debug -DBUILD_SHARED_LIBS=ON -DskipTests
----

Note: To build static libraries use -DBUILD_SHARED_LIBS=OFF

Refer to the table below to select the platform most applicable to your needs.

[cols="4*", options="header"]
|===
|Profile
|Generator
|Config
|Architecture

|windows-amd64-vc11-debug
|Visual Studio 11 Win64
|Debug-x64
|amd64

|windows-amd64-vc11-release
|Visual Studio 11 Win64
|Release-x64
|amd64

|linux-amd64-gcc-debug
|Unix Makefiles
|Debug
|amd64

|linux-amd64-gcc-release
|Unix Makefiles
|Release
|amd64
|===

=== Mapnik Plugin Configuration

==== Mapnik

http://mapnik.org/[Mapnik] is an open source toolkit for developing mapping applications.
GeoWave is supported as a plugin for Mapnik for reading vector data from Accumulo.

Note: These instructions assume that you are using prepackaged binaries.  

==== Configure Scons for Mapnik

To configure Mapnik to run with GeoWave, there are a few SCons options which need to be configured.  Refer to the table below to get an idea for how these options would be configured on Ubuntu 14.04 LTS.

[cols="2*", options="header"]
|===
|Option
|Value

|GEOWAVE_RUNTIME_JAR
|/path/to/geowave/geowave-jace.jar

|GEOWAVE_INCLUDES
|/path/to/geowave/include

|GEOWAVE_LIBS
|/path/to/geowave

|JAVA_INCLUDE_PATH
|/usr/lib/jvm/java-7-oracle/include

|JAVA_INCLUDE_PATH2
|/usr/lib/jvm/java-7-oracle/include/linux

|JAVA_JVM_LIB
|/usr/lib/jvm/java-7-oracle/jre/lib/amd64/server
|===

Note: As Boost is a Mapnik dependency, it should already be included.

==== Build Mapnik

Once SCons is configured, you can proceed with your normal Mapnik build process.

Last, but not least, you should ensure that the libraries specified above are available either via PATH or LD_LIBRARY_PATH.

==== Mapnik Python Tests

In order to run the GeoWave integration test located in python-mapnik, you need to set environment variables defining the locations of the GeoWave runtime and ingest jars.

[source, bash]
----
$ export GEOWAVE_RUNTIME_JAR=/path/to/geowave/geowave-jace.jar
$ export GEOWAVE_INGEST_JAR=/path/to/geowave/geowave-ingest.jar
----

Note: The geowave-ingest jar included in the tarball only works for the geotools-vector format.

=== PDAL Plugin Configuration

==== PDAL  

The Point Data Abstraction Library http://www.pdal.io/index.html[PDAL] is a BSD licensed library for translating
and manipulating point cloud data of various formats.  GeoWave is supported as a plugin for PDAL for both reading
and writing data to Accumulo.  

Note: These instructions assume that you are using prepackaged binaries.  

==== Configure CMake for PDAL

To configure PDAL to run with GeoWave, there are a few CMake options which need to be configured.  While some of the options (namely the JAVA options) may configure automatically, some will need to be set manually.  Refer to the table below to get an idea for how these options would be configured on Ubuntu 14.04 LTS.

[cols="3*", options="header"]
|===
|Option
|Value
|Automatically Configured?

|BUILD_PLUGIN_GEOWAVE
|ON
|

|GEOWAVE_RUNTIME_JAR
|/path/to/geowave/geowave-jace.jar
|

|JACE_INCLUDE_DIR
|/path/to/geowave/include
|

|JACE_LIBRARY
|/path/to/geowave/libjace.so
|

|JAVA_AWT_INCLUDE_PATH
|/usr/lib/jvm/java-7-oracle/include
|X

|JAVA_INCLUDE_PATH
|/usr/lib/jvm/java-7-oracle/include
|X

|JAVA_INCLUDE_PATH2
|/usr/lib/jvm/java-7-oracle/include/linux
|X

|JAVA_AWT_LIBRARY
|/usr/lib/jvm/java-7-oracle/jre/lib/amd64/libjawt.so
|X

|JAVA_JVM_LIBRARY
|/usr/lib/jvm/java-7-oracle/jre/lib/amd64/server/libjvm.so
|X
|===

Note: As Boost is a PDAL dependency, it should already be included.

==== Build PDAL

Once CMake is configured, you can proceed with your normal PDAL build process.

Last, but not least, when building shared libraries you should ensure that the libraries specified above are available via PATH or LD_LIBRARY_PATH.

Within the PDAL documentation, you can see examples of how GeoWave can be used as both a
http://www.pdal.io/stages/readers.geowave.html[reader] and http://www.pdal.io/stages/writers.geowave.html[writer].