[[jace-jni-proxies]]
<<<
== Jace JNI Proxies

Using Jace, we are able to create JNI proxy classes for GeoWave which can be used in C/C++ applications.

=== Prepackaged RPM Setup

Coming Soon...

For a quick and easy setup, you can grab one of our prepackaged RPMs.


=== Manual Setup

If you want to integrate with the latest version of GeoWave or perhaps a specific branch, you can build the Jace proxies yourself.

==== Step 1 - Checkout GeoWave

First, we need to clone GeoWave.

[source, bash]
----
$ git clone git@github.com:ngageoint/geowave.git
----

==== Step 2 - Build GeoWave

In order to generate the Jace proxies, we need to build GeoWave using Maven.

We will also specify two Maven profiles; one which specifies our target platform, and another to specify that we are building Jace proxies.

[source, bash]
----
$ cd geowave
$ mvn clean package -pl geowave-deploy -am -P generate-jace-proxies,linux-amd64-gcc-debug -DskipTests
----

Refer to the table below to select the platform most applicable to your needs.

[cols="4*", options="header"]
|===
|Profile
|Generator
|Config
|Architecture

|windows-amd64-vc11-debug
|Visual Studio 11 Win64
|Debug-x64
|amd64

|windows-amd64-vc11-release
|Visual Studio 11 Win64
|Release-x64
|amd64

|linux-amd64-gcc
|Unix Makefiles
|
|amd64
|===

=== Mapnik Plugin Configuration

==== Mapnik

http://mapnik.org/[Mapnik] is an open source toolkit for developing mapping applications.
GeoWave is supported as a plugin for Mapnik for reading vector data from Accumulo.

==== Configure Scons for Mapnik

Using the manual process described above, you will have generated all of the required artifacts for running GeoWave as a Mapnik plugin.  The artifacts can be found in the target folder within geowave-deploy.

Now that the GeoWave plugin artifacts have been generated, we need to use Scons to configure Mapnik to build with our plugin.

To configure Mapnik to run with GeoWave, there are a few SCons options which need to be configured.  Refer to the table below to get an idea for how these options would be configured using GeoWave v0.8.5 on Ubuntu 14.04 LTS.

[cols="2*", options="header"]
|===
|Option
|Value

|GEOWAVE_RUNTIME_JAR
|/path/to/geowave/geowave-deploy/target/geowave-deploy-0.8.5-jace.jar

|GEOWAVE_JACE_RUNTIME_JAR
|/path/to/geowave/geowave-deploy/target/dependency/jace-core-runtime-1.2.22.jar

|GEOWAVE_INCLUDES
|/path/to/geowave/geowave-deploy/target/dependency/jace/include

|GEOWAVE_LIBS
|/path/to/geowave/geowave-deploy/target/dependency/jace

|JAVA_AWT_INCLUDE_PATH
|/usr/lib/jvm/java-7-oracle/include

|JAVA_INCLUDE_PATH
|/usr/lib/jvm/java-7-oracle/include

|JAVA_INCLUDE_PATH2
|/usr/lib/jvm/java-7-oracle/include/linux

|JAVA_AWT_LIB
|/usr/lib/jvm/java-7-oracle/jre/lib/amd64

|JAVA_JVM_LIB
|/usr/lib/jvm/java-7-oracle/jre/lib/amd64/server
|===

==== Build Mapnik

Once SCons is configured, you can proceed with your normal Mapnik build process.

Last, but not least, you should ensure that the libraries specified above are available either via PATH or LD_LIBRARY_PATH.


=== PDAL Plugin Configuration

==== PDAL  

The Point Data Abstraction Library http://www.pdal.io/index.html[PDAL] is a BSD licensed library for translating
and manipulating point cloud data of various formats.  GeoWave is supported as a plugin for PDAL for both reading
and writing data to Accumulo.  

==== Configure CMake for PDAL

Using the manual process described above, you will have generated all of the required artifacts for running GeoWave as a PDAL plugin.  The artifacts can be found in the target folder within geowave-deploy.

Now that the GeoWave plugin artifacts have been generated, we need to use CMake to configure PDAL to build with our plugin.

To configure PDAL to run with GeoWave, there are a few CMake options which need to be configured.  While some of the options (namely the JAVA options) may configure automatically, some will need to be set manually.  Refer to the table below to get an idea for how these options would be configured using GeoWave v0.8.5 on Ubuntu 14.04 LTS.

[cols="3*", options="header"]
|===
|Option
|Value
|Automatically Configured?

|BUILD_PLUGIN_GEOWAVE
|ON
|

|GEOWAVE_RUNTIME_JAR
|/path/to/geowave/geowave-deploy/target/geowave-deploy-0.8.5-jace.jar
|

|JACE_RUNTIME_JAR
|/path/to/geowave/geowave-deploy/target/dependency/jace-core-runtime-1.2.22.jar
|

|JACE_INCLUDE_DIR
|/path/to/geowave/geowave-deploy/target/dependency/jace/include
|

|JACE_LIBRARY
|/path/to/geowave/geowave-deploy/target/dependency/jace/libjace.so
|

|JAVA_AWT_INCLUDE_PATH
|/usr/lib/jvm/java-7-oracle/include
|X

|JAVA_INCLUDE_PATH
|/usr/lib/jvm/java-7-oracle/include
|X

|JAVA_INCLUDE_PATH2
|/usr/lib/jvm/java-7-oracle/include/linux
|X

|JAVA_AWT_LIBRARY
|/usr/lib/jvm/java-7-oracle/jre/lib/amd64/libjawt.so
|X

|JAVA_JVM_LIBRARY
|/usr/lib/jvm/java-7-oracle/jre/lib/amd64/server/libjvm.so
|X
|===

==== Build PDAL

Once CMake is configured, you can proceed with your normal PDAL build process.

Last, but not least, you should ensure that the libraries specified above are available either via PATH or LD_LIBRARY_PATH.

Within the PDAL documentation, you can see examples of how GeoWave can be used as both a
http://www.pdal.io/stages/readers.geowave.html[reader] and http://www.pdal.io/stages/writers.geowave.html[writer].