[[introduction]]
<<<

:linkattrs:

== Introduction

=== Purpose of this Guide

This guide focuses on the development side of GeoWave. It also serves as a deep dive into some of the inner workings of GeoWave.  The target audience for this guide are GeoWave developers and developers who wish to use GeoWave as part of another software package.

=== Assumptions

This guide assumes the following:

* The reader is familiar with the basics of GeoWave discussed in the link:overview.html[Overview].
* The reader is familiar with the contents of the link:userguide.html[GeoWave User Guide].
* GeoWave has already been installed and is available on the command-line.  See the link:installation-guide.html[Installation Guide^, window="_blank"] for help with the installation process.

=== Development Requirements

GeoWave development requires the following components:

[options="compact"]
* link:https://adoptium.net/[Java Development Kit (JDK), window="_blank"] 21
+
Requires JDK 21. Continuous integration builds and tests with link:https://adoptium.net/[Eclipse Temurin, window="_blank"] 21.
+
Java 8 is supported only by the GeoWave 2.x line, which lives on the link:https://github.com/locationtech/geowave/tree/2.x-jdk8[`2.x-jdk8`, window="_blank"] branch.

* link:http://git-scm.com/[Git, window="_blank"]
+
Reference online material at link:https://git-scm.com/[Git SCM Site, window="_blank"].
+
For a complete reference guide for installing and using Git, please reference chapters in the online link:https://git-scm.com/book/en/v2[Pro Git book, window="_blank"].

* link:https://maven.apache.org/[Maven, window="_blank"]
+
Requires Maven 3.9 or later. Alternatively, use the Maven wrapper committed to the repository (`./mvnw`, or `mvnw.cmd` on Windows), which downloads a suitable Maven version. The commands in this guide use the wrapper.
+
For a reference guide for getting started with Maven, please reference the online link:https://maven.apache.org/guides/getting-started/[Maven Getting Started Guide, window="_blank"].


