[[assumptions]]
<<<
== Assumptions

Prior to setting up a development environment surrounding the GeoWave project, this guide assumes that the following components are installed. Because of the continuous changes occurring to these components, installing, and maintaining, extensive operational capabilities around these components is outside the scope of this document.

=== Development & Building

In order to build and/or perform development using the GeoWave source, the following components are required:

[options="compact"]
* http://www.oracle.com/technetwork/java/javase/downloads/index.html[Java Development Kit (JDK)] (>= 1.8)
+
Requires JDK v1.8 or greater
+
Download from the http://www.oracle.com/technetwork/java/javase/downloads/index.html[Java downloads site]. The OracleJDK is the most thoroughly tested but there are no known issues with OpenJDK.

* http://git-scm.com/[Git]
+
Reference online material at https://git-scm.com/[Git SCM Site].
+
For a complete reference guide for installing and using Git, please reference chapters in the online https://git-scm.com/book/en/v2[Pro Git book].

* https://maven.apache.org/[Maven]
+
Requires a version of Maven >= 3.2.1
+
For a reference guide for getting started with Maven, please reference the online https://maven.apache.org/guides/getting-started/[Maven Getting Started Guide].

* Eclipse IDE
+
Eclipse is used as the primarily supported IDE for editing GeoWave-related source code.
+
For a comprehensive getting started guide with Eclipse, ranging from downloading and installing the most preferred version to extending capabilities well beyond the use within this guide and project, please reference the https://eclipse.org/users/[Eclipse Getting Started Guide].

=== External Components
Depending on the environment components being used in the development and/or operational environment(s), e.g., requirements, datastores, indices, etc., the following are not all required, though constraints are listed below for which versions are supported by GeoWave.

[options="compact"]
* http://geoserver.org/[GeoServer] instance >= 2.5.2
* https://accumulo.apache.org/[Apache Accumulo] version 1.5 or greater is required. 1.5.0, 1.5.1, and 1.6.0 have all
been tested.
* https://hbase.apache.org/[Apache HBase] >= 1.2.1
* http://hadoop.apache.org/[Apache Hadoop] versions 1.x and 2.x
* http://cloudera.com/content/cloudera/en/home.html[Cloudera] CDH4 and CDH5
* http://hortonworks.com/hdp/[Hortonworks Data Platform] 2.1+
* http://www.oracle.com/technetwork/articles/javaee/jai-142803.html[Java Advanced Imaging] and https://docs.oracle.com/javase/8/docs/technotes/guides/imageio/[Java
Image I/O] are also both required to be installed on the GeoServer instance(s) as well as on the Accumulo nodes. The Accumulo support is
only required for certain functions (distributed rendering), so this may be skipped in some cases.

