<<<

:linkattrs:

[[building]]
== Building the Source

[[build-geowave]]
=== Building GeoWave

Building GeoWave requires JDK 21 (see <<005-introduction.adoc#development-requirements, Development Requirements>>). To build the project source, navigate to the root directory of the GeoWave project using a command-line tool and execute the following Maven command:

[source, bash]
----
$ ./mvnw clean install <1>
----
<1> You can speed up the build by skipping unit tests and bug checks by adding `-Dspotbugs.skip -DskipTests`

NOTE: Use `clean` when rebuilding. The HBase and raster modules generate protobuf sources into `src/main/java`, and the HBase step rewrites its copies of the `.proto` files under `target` before compiling them, so a rebuild over a dirty tree can produce doubled class names such as `AggregationProtosClientClient`.

After executing the command, Maven will search for all of the projects that need to be built and begin the build process.  The initial output of the command should look something like the following:

----
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] GeoWave Parent POM
[INFO] GeoWave Core Parent POM
[INFO] GeoWave CLI
[INFO] GeoWave Index
[INFO] GeoWave Store
.
.
.
----

The build process can take several minutes, but once this is completed, the compiled artifacts for each project will be installed to your local Maven repository. They will also be available in each project's `target` directory.

==== Apple Silicon

All modules build on Apple Silicon, but the protoc compilers and gRPC code generator that the build pins have no `osx-aarch_64` binaries. Their `osx-x86_64` binaries run under Rosetta, so the build has to be pointed at those:

* The raster and HBase modules pin protoc 2.5.0 for HBase wire compatibility. Its x86_64 binary is bundled in the `protoc-jar` artifact.
* The gRPC modules use protoc 3.17.1 together with the `protoc-gen-grpc-java` 1.38.0 code generator plugin.

Fetch the x86_64 binaries and make them executable:

[source, bash]
----
$ mkdir -p /tmp/protoc
$ curl -fsSL -o /tmp/protoc/protoc-jar-3.11.4.jar \
    https://repo1.maven.org/maven2/com/github/os72/protoc-jar/3.11.4/protoc-jar-3.11.4.jar
$ unzip -o -j /tmp/protoc/protoc-jar-3.11.4.jar 'bin/2.5.0/protoc-2.5.0-osx-x86_64.exe' -d /tmp/protoc
$ curl -fsSL -o /tmp/protoc/protoc-3.17.1-osx-x86_64.exe \
    https://repo1.maven.org/maven2/com/google/protobuf/protoc/3.17.1/protoc-3.17.1-osx-x86_64.exe
$ curl -fsSL -o /tmp/protoc/protoc-gen-grpc-java-1.38.0-osx-x86_64.exe \
    https://repo1.maven.org/maven2/io/grpc/protoc-gen-grpc-java/1.38.0/protoc-gen-grpc-java-1.38.0-osx-x86_64.exe
$ chmod +x /tmp/protoc/*.exe
----

IMPORTANT: The executable bit matters. If the file given to `-DprotocCommand` cannot be run, it is silently ignored, as if the property had never been set, and the build falls back to looking for an `osx-aarch_64` protoc. For protoc 2.5.0 that fails with `Unsupported platform`.

The build is pointed at a protoc binary with `-DprotocCommand`, but there is no equivalent property for the gRPC code generator plugin. Instead, put the x86_64 plugin into your local Maven repository under the `osx-aarch_64` classifier, where the build looks for it:

[source, bash]
----
$ mkdir -p ~/.m2/repository/io/grpc/protoc-gen-grpc-java/1.38.0
$ cp /tmp/protoc/protoc-gen-grpc-java-1.38.0-osx-x86_64.exe \
    ~/.m2/repository/io/grpc/protoc-gen-grpc-java/1.38.0/protoc-gen-grpc-java-1.38.0-osx-aarch_64.exe
----

`-DprotocCommand` applies to every module in the build, and the modules need different protoc versions, so a full build takes two passes: protoc 2.5.0 for everything except the gRPC protobuf and server modules and the integration tests, then protoc 3.17.1 for those three.

[source, bash]
----
$ ./mvnw clean install -DskipTests -Dspotbugs.skip \
    -DprotocCommand=/tmp/protoc/protoc-2.5.0-osx-x86_64.exe \
    -pl '!services/grpc/protobuf,!services/grpc/server,!test'
$ ./mvnw clean install -DskipTests -Dspotbugs.skip \
    -DprotocCommand=/tmp/protoc/protoc-3.17.1-osx-x86_64.exe \
    -pl services/grpc/protobuf,services/grpc/server,test
----

[WARNING]
====
The raster and HBase modules generate their protobuf sources into `src/main/java` rather than `target`, and the HBase module rewrites the protobuf package in those sources in place, so `clean` cannot remove them. A single build of these modules with the wrong protoc leaves mis-shaded sources behind that break every later build until they are deleted by hand. The symptom is `package org.apache.hadoop.hbase.shaded.com.google.protobuf.GeneratedMessageV3 does not exist`. To recover, delete the generated sources and rebuild:

[source, bash]
----
$ rm -rf extensions/adapters/raster/src/main/java/org/locationtech/geowave/adapter/raster/protobuf \
    extensions/datastores/hbase/core/src/main/java/org/locationtech/geowave/datastore/hbase/coprocessors/protobuf \
    extensions/datastores/hbase/core/src/main/java/org/locationtech/geowave/datastore/hbase/query/protobuf
----
====

Once both passes have completed, run the integration tests on the `test` module alone, with the protoc 3.17.1 binary. Adding `-am`, as CI does, would rebuild the raster and HBase modules with that protoc as well. `rocksdbjni` includes an `osx-arm64` native library, so RocksDB, and with it the `rocksdb-it` profile, runs natively on Apple Silicon:

[source, bash]
----
$ ./mvnw verify -pl test -Procksdb-it \
    -Dtest=SkipUnitTests -DfailIfNoTests=false -Dsurefire.failIfNoSpecifiedTests=false -Dspotbugs.skip \
    -DprotocCommand=/tmp/protoc/protoc-3.17.1-osx-x86_64.exe
----

CI also puts Hadoop's Linux native libraries on `LD_LIBRARY_PATH`. There is no macOS build of them, and the integration tests do not need them.

=== Running Integration Tests

By default, integration tests are not run as part of the normal build process.  This is because integration tests can be run for a multitude of key/value store backends, and tests for a single backend can take a significant amount of time to complete.  Usually these integration tests are run through link:https://github.com/locationtech/geowave/actions/workflows/test.yml[GitHub Actions, window="_blank"], but it can be useful to run them locally when working on code that could potentially impact one of the tests.

Integration tests are all written in the `geowave-test` project and are run using a series of Maven profiles.  The following table shows the various profiles available along with a description of the tests that are run:

[options="header", cols="25%,75%"]
|======================
| Maven Profile      | Description 
| accumulo-it-client | Run integration tests on Accumulo with server-side libraries disabled
| accumulo-it-server | Run integration tests on Accumulo with server-side libraries enabled
| accumulo-it-all    | Run integration tests on Accumulo with server-side libraries enabled and disabled
| cassandra-it       | Run integration tests on Cassandra
| dynamodb-it        | Run integration tests on DynamoDB
| filesystem-it      | Run integration tests on the filesystem store
| hbase-it-client    | Run integration tests on HBase with server-side libraries disabled
| hbase-it-server    | Run integration tests on HBase with server-side libraries enabled
| hbase-it-all       | Run integration tests on HBase with server-side libraries enabled and disabled
| redis-it           | Run integration tests on Redis
| rocksdb-it         | Run integration tests on RocksDB
| secondary-index-it | Run integration tests with secondary indexing enabled, this profile can be used with any of the previous profiles
|======================

In order to use one of these profiles to run integration tests, use the same command that was used to build the source, but add the appropriate profile to the end.  For example, if you wanted to run integration tests for RocksDB, the command would look like the following:

[source, bash]
----
$ ./mvnw clean install -Procksdb-it
----

If you have already built GeoWave, you can skip straight to the integration tests:

[source, bash]
----
$ ./mvnw clean install -rf :geowave-test -Procksdb-it
----

[[build-python-bindings]]
=== Building Python Bindings

The Python bindings for GeoWave (`pygw`) use a different build process than the Java component. The Python source code for `pygw` can be found in the `python/src/main/python` directory.  In order to install `pygw` from source, you will need link:https://www.python.org[Python 3.8 or later, window="_blank"]. Continuous integration builds it on Python 3.12.

==== Building the Wheel

Navigate to Python source directory `python/src/main/python` in your command-line tool and perform the following steps.

Create the virtual environment:

[source, bash]
----
$ python3 -m venv venv
----

Activate the environment:

[source, bash]
----
$ source venv/bin/activate
----

Install requirements in the activated python virtual environment:
----
$ pip install -r requirements.txt
----

Install necessary build tools:

[source, bash]
----
$ pip install --upgrade pip wheel setuptools twine
----

Build the wheel:

[source, bash]
----
$ python setup.py bdist_wheel --python-tag=py3 sdist
----

==== Installing the Wheel

After performing the steps in the build step, a `.whl` file should be written to the `dist` directory.  To install it, simply perform the `pip install` command on that file:

[source, bash]
----
$ pip install dist/pygw-*.whl
----

NOTE: If you have multiple wheel builds in the `dist` directory, use the full filename of the `.whl` you wish to install.

==== Running Tests

In order to run tests for `pygw`, a GeoWave Py4J Java Gateway needs to be running.  GeoWave offers a simple CLI command to run a gateway.  In a separate window, execute the following command:

[source, bash]
----
$ geowave util python rungateway 
----

NOTE: The gateway command is included in the CLI tools JAR. See <<020-packaging.adoc#geowave-cli-tools, GeoWave CLI Tools>> for how to package it and run it as `geowave`.

While this gateway is running, execute the following command to run the tests:

[source, bash]
----
$ python -m pytest
----

[[build-docs]]
=== Building Docs

GeoWave documentation consists of several different parts, the main documentation, which includes this guide, the Javadocs, and the Python bindings documentation.

==== GeoWave Documentation

GeoWave documentation is primarily written with link:https://asciidoctor.org[Asciidoctor, window="_blank"] and can be built using a single Maven command from the GeoWave root directory. Like the rest of the build, this requires JDK 21.

[source, bash]
----
$ ./mvnw -P html -pl docs install -DskipTests -Dspotbugs.skip
----

This command compiles all documentation as HTML and outputs it to the `target/site` directory.

NOTE: PDF output is also supported by replacing `-P html` in the above command with `-P pdf`.

==== Javadocs

Javadocs for all projects can be built using the following command:

[source, bash]
----
$ ./mvnw -q javadoc:aggregate -DskipTests -Dspotbugs.skip
----

This command will output all of the Javadocs to the `target/site/apidocs` directory.

==== Python Bindings Documentation

They GeoWave Python bindings been documented using Python docstrings. In order to generate this documentation, a Python environment should be set up and the GeoWave Py4J Java Gateway should be running, see <<015-building.adoc#build-python-bindings, Build Python Bindings>> for help with this.  Once the environment is activated an the gateway is running, execute the following command from the `python/src/main/python` directory to generate the documentation:

[source, bash]
----
$ pdoc --html pygw
----

This will generate the Python API documentation in the `python/src/main/python/html/pygw` directory.
