<<<

:linkattrs:

[[building]]
== Building the Source

[[build-geowave]]
=== Building GeoWave

Building GeoWave requires JDK 21 (see <<005-introduction.adoc#development-requirements, Development Requirements>>). To build the project source, navigate to the root directory of the GeoWave project using a command-line tool and execute the following Maven command:

[source, bash]
----
$ ./mvnw clean install <1>
----
<1> You can speed up the build by skipping unit tests and bug checks by adding `-Dspotbugs.skip -DskipTests`

After executing the command, Maven will search for all of the projects that need to be built and begin the build process.  The initial output of the command should look something like the following:

----
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] GeoWave Parent POM
[INFO] GeoWave Core Parent POM
[INFO] GeoWave CLI
[INFO] GeoWave Index
[INFO] GeoWave Store
.
.
.
----

The build process can take several minutes, but once this is completed, the compiled artifacts for each project will be installed to your local Maven repository. They will also be available in each project's `target` directory.

==== Checkouts built before GeoWave 3.0

Builds before GeoWave 3.0 wrote generated sources into the source tree: protobuf classes under `src/main/java` in `extensions/adapters/raster` and `extensions/datastores/hbase/core`, and gRPC `.proto` files and classes under `services/grpc/protobuf/src`. The build now generates all of them under `target`, so a checkout that still has the old copies fails to compile with `duplicate class` errors. `mvn clean` does not reach them. They are untracked files, so `git clean` removes them without touching anything under version control:

[source, bash]
----
$ git clean -fd extensions/adapters/raster/src extensions/datastores/hbase/core/src services/grpc/protobuf/src
----

==== Apple Silicon

The build runs in a single pass on Apple Silicon. The gRPC modules use the `osx-aarch_64` builds of protoc and of the `protoc-gen-grpc-java` code generator. The raster and HBase modules generate their protobuf classes with protoc 2.5.0, to match the protobuf-java 2.5.0 that HBase 2 region servers run, and protoc 2.5.0 was only built for x86: on macOS the build uses its `osx-x86_64` binary, which runs under Rosetta 2. If Rosetta is not installed, install it once; without it the raster module, the first to run protoc 2.5.0, fails.

[source, bash]
----
$ softwareupdate --install-rosetta --agree-to-license
----

`rocksdbjni` includes an `osx-arm64` native library, so RocksDB, and with it the `rocksdb-it` profile, runs natively on Apple Silicon:

[source, bash]
----
$ ./mvnw verify -am -pl test -Procksdb-it \
    -Dtest=SkipUnitTests -DfailIfNoTests=false -Dsurefire.failIfNoSpecifiedTests=false -Dspotbugs.skip
----

CI also puts Hadoop's Linux native libraries on `LD_LIBRARY_PATH`. There is no macOS build of them, and the integration tests do not need them.

=== Running Integration Tests

By default, integration tests are not run as part of the normal build process.  This is because integration tests can be run for a multitude of key/value store backends, and tests for a single backend can take a significant amount of time to complete.  Usually these integration tests are run through link:https://github.com/locationtech/geowave/actions/workflows/test.yml[GitHub Actions, window="_blank"], but it can be useful to run them locally when working on code that could potentially impact one of the tests.

Integration tests are all written in the `geowave-test` project and are run using a series of Maven profiles.  The following table shows the various profiles available along with a description of the tests that are run:

[options="header", cols="25%,75%"]
|======================
| Maven Profile      | Description 
| accumulo-it-client | Run integration tests on Accumulo with server-side libraries disabled
| accumulo-it-server | Run integration tests on Accumulo with server-side libraries enabled
| accumulo-it-all    | Run integration tests on Accumulo with server-side libraries enabled and disabled
| cassandra-it       | Run integration tests on Cassandra
| dynamodb-it        | Run integration tests on DynamoDB
| filesystem-it      | Run integration tests on the filesystem store
| hbase-it-client    | Run integration tests on HBase with server-side libraries disabled
| hbase-it-server    | Run integration tests on HBase with server-side libraries enabled
| hbase-it-all       | Run integration tests on HBase with server-side libraries enabled and disabled
| redis-it           | Run integration tests on Redis
| rocksdb-it         | Run integration tests on RocksDB
| secondary-index-it | Run integration tests with secondary indexing enabled, this profile can be used with any of the previous profiles
|======================

In order to use one of these profiles to run integration tests, use the same command that was used to build the source, but add the appropriate profile to the end.  For example, if you wanted to run integration tests for RocksDB, the command would look like the following:

[source, bash]
----
$ ./mvnw clean install -Procksdb-it
----

If you have already built GeoWave, you can skip straight to the integration tests:

[source, bash]
----
$ ./mvnw clean install -rf :geowave-test -Procksdb-it
----

[[build-python-bindings]]
=== Building Python Bindings

The Python bindings for GeoWave (`pygw`) use a different build process than the Java component. The Python source code for `pygw` can be found in the `python/src/main/python` directory.  In order to install `pygw` from source, you will need link:https://www.python.org[Python 3.8 or later, window="_blank"]. Continuous integration builds it on Python 3.12.

==== Building the Wheel

Navigate to Python source directory `python/src/main/python` in your command-line tool and perform the following steps.

Create the virtual environment:

[source, bash]
----
$ python3 -m venv venv
----

Activate the environment:

[source, bash]
----
$ source venv/bin/activate
----

Install requirements in the activated python virtual environment:
----
$ pip install -r requirements.txt
----

Install necessary build tools:

[source, bash]
----
$ pip install --upgrade pip wheel setuptools twine
----

Build the wheel:

[source, bash]
----
$ python setup.py bdist_wheel --python-tag=py3 sdist
----

==== Installing the Wheel

After performing the steps in the build step, a `.whl` file should be written to the `dist` directory.  To install it, simply perform the `pip install` command on that file:

[source, bash]
----
$ pip install dist/pygw-*.whl
----

NOTE: If you have multiple wheel builds in the `dist` directory, use the full filename of the `.whl` you wish to install.

==== Running Tests

In order to run tests for `pygw`, a GeoWave Py4J Java Gateway needs to be running.  GeoWave offers a simple CLI command to run a gateway.  In a separate window, execute the following command:

[source, bash]
----
$ geowave util python rungateway 
----

NOTE: The gateway command is included in the CLI tools JAR. See <<020-packaging.adoc#geowave-cli-tools, GeoWave CLI Tools>> for how to package it and run it as `geowave`.

While this gateway is running, execute the following command to run the tests:

[source, bash]
----
$ python -m pytest
----

[[build-docs]]
=== Building Docs

GeoWave documentation consists of several different parts, the main documentation, which includes this guide, the Javadocs, and the Python bindings documentation.

==== GeoWave Documentation

GeoWave documentation is primarily written with link:https://asciidoctor.org[Asciidoctor, window="_blank"] and can be built using a single Maven command from the GeoWave root directory. Like the rest of the build, this requires JDK 21.

[source, bash]
----
$ ./mvnw -P html -pl docs install -DskipTests -Dspotbugs.skip
----

This command compiles all documentation as HTML and outputs it to the `target/site` directory.

NOTE: PDF output is also supported by replacing `-P html` in the above command with `-P pdf`.

==== Javadocs

Javadocs for all projects can be built using the following command:

[source, bash]
----
$ ./mvnw -q javadoc:aggregate -DskipTests -Dspotbugs.skip
----

This command will output all of the Javadocs to the `target/site/apidocs` directory.

==== Python Bindings Documentation

They GeoWave Python bindings been documented using Python docstrings. In order to generate this documentation, a Python environment should be set up and the GeoWave Py4J Java Gateway should be running, see <<015-building.adoc#build-python-bindings, Build Python Bindings>> for help with this.  Once the environment is activated an the gateway is running, execute the following command from the `python/src/main/python` directory to generate the documentation:

[source, bash]
----
$ pdoc --html pygw
----

This will generate the Python API documentation in the `python/src/main/python/html/pygw` directory.
