<<<

:linkattrs:

[[packaging]]
== Packaging GeoWave Builds

GeoWave can be packaged in several different ways.  Prior to packaging GeoWave, make sure that the build process has completed.

=== GeoWave CLI Tools

GeoWave artifacts can be packaged into a single JAR that can be used to execute CLI commands by running the following Maven command from the GeoWave root directory:

[source, bash]
----
$ ./mvnw package -P geowave-tools-singlejar -Dspotbugs.skip -DskipTests
----

After the packaging process is complete, the resulting JAR will be available in the `deploy/target` directory with a name like `geowave-deploy-<version>-tools.jar`.  To use this jar for CLI commands you can execute it using the following java command:

[source, bash]
----
$ java -cp <geowave_home>/deploy/target/geowave-deploy-${project.version}-tools.jar org.locationtech.geowave.core.cli.GeoWaveMain <command> <options>
----

NOTE: Replace `<geowave_home>` with the GeoWave home directory, or use an environment variable.

As you can see, using GeoWave in this way can be fairly cumbersome.  To make things easier, this command can be wrapped up in an alias.

.Linux, Mac, Windows w/ Git Bash
[source, bash]
----
$ alias geowave="java -cp $GEOWAVE_HOME/deploy/target/geowave-deploy-${project.version}-tools.jar org.locationtech.geowave.core.cli.GeoWaveMain"
----

.Windows Command Prompt
[source, bash]
----
$ doskey geowave=java -cp %GEOWAVE_HOME%/deploy/target/geowave-deploy-${project.version}-tools.jar org.locationtech.geowave.core.cli.GeoWaveMain $*
----

After the alias has been created, you will be able to use the GeoWave CLI with the `geowave` command. For a full list of these commands, please see the link:commands.html[GeoWave CLI Appendix, window="_blank"].

Of the commands that run a local server for testing, the tools JAR includes only `geowave gs run` (from `extensions/cli/geoserver-embed`).  It does not bundle GeoServer itself: it runs a GeoServer ${geoserver.version} WAR unpacked on disk, with the tools JAR ahead of the WAR's own `WEB-INF/lib` on the web application's classpath, as described in link:quickstart.html#run-geoserver[Run GeoServer^, window="_blank"].  It listens on 127.0.0.1 by default, and is meant for local evaluation only.  The Accumulo, Cassandra, DynamoDB, HBase and Redis `util <store> run` commands are not packaged into the tools JAR; their `geowave-cli-<store>-embed` modules are used by the integration tests.

=== GeoServer Plugin

GeoWave artifacts can be packaged into a single JAR to be used in a GeoServer installation by running the following Maven command from the GeoWave root directory:

[source, bash]
----
$ ./mvnw package -P geotools-container-singlejar -Dspotbugs.skip -DskipTests
----

After the packaging process is complete, the resulting JAR will be available in the `deploy/target` directory with a name like `geowave-deploy-<version>-geoserver.jar`. To use this jar with a GeoServer installation, simply copy it to the `WEB-INF/lib` directory of GeoServer's installation and restart the web service that GeoServer is running on.

=== Accumulo JAR

GeoWave artifacts can be packaged into a JAR to be used by Accumulo for server-side operations by running the following Maven command from the GeoWave root directory:

[source, bash]
----
$ ./mvnw package -P accumulo-container-singlejar -Dspotbugs.skip -DskipTests
----

After the packaging process is complete, the resulting JAR will be available in the `deploy/target` directory with a name like `geowave-deploy-<version>-accumulo.jar`. See link:userguide.html#accumulo-config[Accumulo Configuration, window="_blank"] in the User Guide for more information about using this jar.

=== HBase Coprocessor JAR

GeoWave artifacts can be packaged into a coprocessor JAR for HBase server-side operations by running the following Maven command from the GeoWave root directory:

[source, bash]
----
$ ./mvnw package -P hbase-container-singlejar -Dspotbugs.skip -DskipTests
----

After the packaging process is complete, the resulting JAR will be available in the `deploy/target` directory with a name like `geowave-deploy-<version>-hbase.jar`. In order to use this jar, copy it to an HDFS location that is accessible to HBase. When configuring the GeoWave HBase data store (either through the GeoServer plugin or the CLI), set the `coprocessorJar` option to the HDFS location of the jar.
