[[ingest-statistics]]
=== Ingest Statistics and Time Dimension Configuration

:linkattrs:

The available plugins for vector support adjustments to their configuration via the command line.
The system property 'SIMPLE_FEATURE_CONFIG_FILE' may be assigned to the name of a locally accessible JSON file defining
the configuration.

==== Example
[source]
----
$ GEOWAVE_TOOL_JAVA_OPT="-DSIMPLE_FEATURE_CONFIG_FILE=myconfigfile.json"
$ geowave ingest localtogw ./ingest mystore myindex
----

Configuration consists of several parts:
[arabic]
. Selecting temporal attributes for a temporal index.
. Assigning to each attribute the type of statistics to be captured within the statistics store.
. Determining which attributes should be indexed in a secondary index.
. Determining which attribute contains visibility information for other attributes
. Setting the names of the indices to update in WFS-T transactions via the GeoServer plug-in.

The JSON file is made up of configurations. Each configuration is defined by a class name and a set of attributes.
Configurations are grouped by the Simple Feature Type name.

==== Temporal Configuration

There three attributes for the temporal configuration are:
[arabic]
. timeName
. startRangeName
. endRangeName

These attributes are associated with the name of a simple feature type attribute that references a time value. To index by a single time attribute, set `_timeName_` to the name of the single attribute.  To index by a range, set both `_startRangeName_` and `_endRangeName_` to the names of the simple feature type attributes that define start and end time values.

==== Statistics Configuration

Each simple feature type attribute may have several assigned statistics. Bounding box and range statistics are automatically captured for geometry and temporal attributes.

[frame="topbot", width="100%", cols="12%,25%,20%,43%", grid="rows", options="header"]
|=========================================================
|Attribute Type | Statistic Name|Statistic Configuration Attributes (with default values)|Statistic Class
.3+| Numeric
| Fixed Bin Histogram | minValue=-&#8734;, maxValue=&#8734;, bins=32 | link:https://github.com/locationtech/geowave/blob/master/extensions/adapters/vector/src/main/java/mil/nga/giat/geowave/adapter/vector/stats/FeatureFixedBinNumericStatistics.java#L130[mil.nga.giat.geowave.adapter.vector.stats.
FeatureFixedBinNumericStatistics$FeatureFixedBinConfig, window="_blank"]

| Dynamic Histogram | | link:https://github.com/locationtech/geowave/blob/master/extensions/adapters/vector/src/main/java/mil/nga/giat/geowave/adapter/vector/stats/FeatureNumericHistogramStatistics.java#L356[mil.nga.giat.geowave.adapter.vector.stats.
FeatureNumericHistogramStatistics$FeatureNumericHistogramConfig, window="_blank"]

| Numeric Range | | link:https://github.com/locationtech/geowave/blob/master/extensions/adapters/vector/src/main/java/mil/nga/giat/geowave/adapter/vector/stats/FeatureNumericRangeStatistics.java#L128[mil.nga.giat.geowave.adapter.vector.stats.
FeatureNumericRangeStatistics$FeatureNumericRangeConfig, window="_blank" ]

.2+| String
| Count Min Sketch | errorFactor=0.001, probabilityOfCorrectness=0.98 | link:https://github.com/locationtech/geowave/blob/master/extensions/adapters/vector/src/main/java/mil/nga/giat/geowave/adapter/vector/stats/FeatureCountMinSketchStatistics.java#L203[mil.nga.giat.geowave.adapter.vector.stats.
FeatureCountMinSketchStatistics$FeatureCountMinSketchConfig, window="_blank"]

| Hyper Log Log | precision=16 | link:https://github.com/locationtech/geowave/blob/master/extensions/adapters/vector/src/main/java/mil/nga/giat/geowave/adapter/vector/stats/FeatureHyperLogLogStatistics.java#L205[mil.nga.giat.geowave.adapter.vector.stats.
FeatureHyperLogLogStatistics$FeatureHyperLogLogConfig, window="_blank"]

|=========================================================

==== Visibility Configuration

Visibility configuration has two attributes: the visibility manager class and the visibility attribute name.

A Visibility manager extends _link:https://github.com/locationtech/geowave/blob/master/core/store/src/main/java/mil/nga/giat/geowave/core/store/data/visibility/VisibilityManagement.java[mil.nga.giat.geowave.core.store.data.visibility.VisibilityManagement, window="_blank"]_. An instance of this class interprets the contents of a visibility attribute, within a simple feature, to determine the visibility constraints of the other attributes in that simple feature. The default visibility management class is _link:https://github.com/locationtech/geowave/blob/master/extensions/adapters/vector/src/main/java/mil/nga/giat/geowave/adapter/vector/plugin/visibility/JsonDefinitionColumnVisibilityManagement.java[mil.nga.giat.geowave.adapter.vector.plugin.visibility.JsonDefinitionColumnVisibilityManagement, window="_blank"]_.

==== Secondary Index Configuration

Secondary Index Configurations is made up of one of these three classes:

* _link:https://github.com/locationtech/geowave/blob/master/extensions/adapters/vector/src/main/java/mil/nga/giat/geowave/adapter/vector/index/NumericSecondaryIndexConfiguration.java[mil.nga.giat.geowave.adapter.vector.index.NumericSecondaryIndexConfiguration, window="_blank"]_
* _link:https://github.com/locationtech/geowave/blob/master/extensions/adapters/vector/src/main/java/mil/nga/giat/geowave/adapter/vector/index/TemporalSecondaryIndexConfiguration.java[mil.nga.giat.geowave.adapter.vector.index.TemporalSecondaryIndexConfiguration, window="_blank"]_
* _link:https://github.com/locationtech/geowave/blob/master/extensions/adapters/vector/src/main/java/mil/nga/giat/geowave/adapter/vector/index/TextSecondaryIndexConfiguration.java[mil.nga.giat.geowave.adapter.vector.index.TextSecondaryIndexConfiguration, window="_blank"]_

Each of this configurations maintains a set of simple feature attribute names to index in a secondary index.

==== Primary Index Identifiers

The class _link:https://github.com/locationtech/geowave/blob/master/extensions/adapters/vector/src/main/java/mil/nga/giat/geowave/adapter/vector/index/SimpleFeaturePrimaryIndexConfiguration.java[mil.nga.giat.geowave.adapter.vector.index.SimpleFeaturePrimaryIndexConfiguration, window="_blank"]_ is used to maintain the configuration of primary indices used for adding or updating simple features via the GeoServer plug-in (FeatureWriter).

==== Example
[source]
----
{
  "configurations": {
     "myFeatureTypeName" : [
       {
        "@class" : "mil.nga.giat.geowave.adapter.vector.utils.TimeDescriptors$TimeDescriptorConfiguration",
        "startRangeName" : null,
        "endRangeName" : null,
        "timeName" : "captureTime"
       },
       {
         "@class" : "mil.nga.giat.geowave.adapter.vector.index.NumericSecondaryIndexConfiguration",
         "attributes" : ["pop"]
       },
       {
         "@class" : "mil.nga.giat.geowave.adapter.vector.plugin.visibility.VisibilityConfiguration",
         "attributeName" : "vis"
       },
       {
         "@class" : "mil.nga.giat.geowave.adapter.vector.index.SimpleFeaturePrimaryIndexConfiguration",
         "indexNames" : ["SPATIAL_IDX"]
       }
       {
        "@class" : "mil.nga.giat.geowave.adapter.vector.stats.StatsConfigurationCollection$SimpleFeatureStatsConfigurationCollection",
        "attConfig" : {
          "population" : {
            "configurationsForAttribute" :  [
              {
                "@class" : "mil.nga.giat.geowave.adapter.vector.stats.FeatureFixedBinNumericStatistics$FeatureFixedBinConfig",
                "bins" : 24
              }
             ]
            },
          "country" : {
            "configurationsForAttribute" :  [
             {
              "@class" : "mil.nga.giat.geowave.adapter.vector.stats.FeatureCountMinSketchStatistics$FeatureCountMinSketchConfig",
              "probabilityOfCorrectness" : 0.98,
              "errorFactor" : 0.001
             },
             {
               "@class" : "mil.nga.giat.geowave.adapter.vector.stats.FeatureHyperLogLogStatistics$FeatureHyperLogLogConfig"
             }
            ]
          }
        }
      }
    ]
  }
}

----
