[[ingest-new-formats]]
<<<
[[ingest-new-formats]]
=== New Formats

:linkattrs:

When trying to ingest new data formats, new ingest plugins need to be written to interface with the different data types. Format plugins _hook_ into the ingest framework and allow decoupling from the datastores, e.g., accumulo or hbase, and an index. Generally the intent is to limit a format plugin to what it takes to translate raw files into GeoWave rows. For vector data, geowave rows implies the GeoTools' SimpleFeature object and for raster it implies the GeoTools' GridCoverage object. Additionally, a data format can supply a translation from a file to any custom schema, which will be in turn used as an intermediate format to support distributed ingest.

Ingest plugins should extend the https://github.com/locationtech/geowave/blob/master/extensions/adapters/vector/src/main/java/mil/nga/giat/geowave/adapter/vector/ingest/AbstractSimpleFeatureIngestPlugin.java[AbstractSimpleFeatureIngestPlugin, window="_blank"].

Any of our extensions/formats projects are good examples for extensible new formats that can be discovered at runtime, such as the https://github.com/locationtech/geowave/blob/master/extensions/formats/avro/src/main/java/mil/nga/giat/geowave/format/avro/AvroIngestPlugin.java[AvroIngestPlugin, window="_blank"], or any of the other existing ingest plugins, such as those listed below:

* AbstractSimpleFeatureIngestPlugin
** https://github.com/locationtech/geowave/blob/master/extensions/formats/avro/src/main/java/mil/nga/giat/geowave/format/avro/AvroIngestPlugin.java[AvroIngestPlugin, window="_blank"]
** https://github.com/locationtech/geowave/blob/master/extensions/formats/gdelt/src/main/java/mil/nga/giat/geowave/format/gdelt/GDELTIngestPlugin.java[GDELTIngestPlugin, window="_blank"]
** https://github.com/locationtech/geowave/blob/master/extensions/formats/geolife/src/main/java/mil/nga/giat/geowave/format/geolife/GeoLifeIngestPlugin.java[GeoLifeIngestPlugin, window="_blank"]
** https://github.com/locationtech/geowave/blob/master/extensions/formats/gpx/src/main/java/mil/nga/giat/geowave/format/gpx/GpxIngestPlugin.java[GpxIngestPlugin, window="_blank"]
** https://github.com/locationtech/geowave/blob/master/extensions/formats/tdrive/src/main/java/mil/nga/giat/geowave/format/tdrive/TdriveIngestPlugin.java[TdriveIngestPlugin, window="_blank"]
** https://github.com/locationtech/geowave/blob/master/extensions/formats/twitter/src/main/java/mil/nga/giat/geowave/format/twitter/TwitterIngestPlugin.java[TwitterIngestPlugin, window="_blank"]

