[[analytics-overview]]
== Analytics

:linkattrs:

=== Overview

Analytics embody algorithms tailored to geospatial data.  Most analytics leverage Hadoop MapReduce for bulk computation.
Results of analytic jobs consist of vector or raster data stored in GeoWave.  The analytics infrastructure provides tools to
build algorithms in Spark.  For example, a Kryo serializer/deserializer enables exchange of SimpleFeatures and the GeoWaveInputFormat
supplies data to the Hadoop RDD.

[NOTE]
====
GeoWaveInputFormat does not remove duplicate features that reference polygons spanning multiple index regions.
====

The following algorithms are provided:

[width="100%",cols="2,10",options="header"]
|=========================================================
|Name |Description
|KMeans++|
A K-Means implementation to find K centroids over the population of data.
A set of preliminary sampling iterations find an optimal value of K and the an initial set of K centroids.
The algorithm produces K centroids and their associated polygons.  Each polygon represents the concave hull
containing all features associated with a centroid.
The algorithm supports drilling down multiple levels. At each level, the set centroids are determined
from the set of features associated the same centroid from the previous level.
|KMeans Jump|
Uses KMeans++ over a range of k, choosing an optimal k using an information theoretic based measurement.
|KMeans Parallel|
Performs a KMeans Parallel Cluster
|DBScan|
The Density Based Scanner algorithm produces a set of convex polygons for each region meeting density criteria.
Density of region is measured by a minimum cardinality of enclosed features within a specified distance from each other.
|Nearest Neighbors|
A infrastructure component that produces all the neighbors of a feature within a specific distance.
|=========================================================

=== Building

Build the GeoWave tools project as explained in the <<012-building-code.adoc#building-tools-framework, "ToolsFramework -> Building" section>>.

=== Running

[source, bash]
----
yarn jar geowave-tools.jar analytic <algorithm> <options> <store>
----

The above command will execute <algorithm> (such as dbscan), sourcing the data from the <store> datastore (see link:commands.html#config-addstore[config addstore in the GeoWave CLI commands, window="_blank"]).
