[[api-examples]]
<<<

== Programmatic API Examples

The following examples show how to utilize the GeoWave API to accomplish common tasks programmatically.

=== Creating Data Stores

Data stores are created by instantiating a {core-store}/core/store/StoreFactoryOptions.java[`StoreFactoryOptions`] implementation for the data store type you want to create.  The following table lists the various options classes for each supported key/value store:

[options="header", cols="25%,75%"]
|======================
| Key/Value Store | Options Class
| Accumulo        | {store-accumulo}/datastore/accumulo/config/AccumuloRequiredOptions.java[`org.locationtech.geowave.datastore.accumulo.config.AccumuloRequiredOptions`]
| Bigtable        | {store-bigtable}/datastore/bigtable/config/BigTableOptions.java[`org.locationtech.geowave.datastore.bigtable.config.BigTableOptions`]
| Cassandra       | {store-cassandra}/datastore/cassandra/config/CassandraRequiredOptions.java[`org.locationtech.geowave.datastore.cassandra.config.CassandraRequiredOptions`]
| DynamoDB        | {store-dynamodb}/datastore/dynamodb/config/DynamoDBOptions.java[`org.locationtech.geowave.datastore.dynamodb.config.DynamoDBOptions`]
| HBase           | {store-hbase}/datastore/hbase/config/HBaseRequiredOptions.java[`org.locationtech.geowave.datastore.hbase.config.HBaseRequiredOptions`]
| Kudu            | {store-kudu}/datastore/kudu/config/KuduOptions.java[`org.locationtech.geowave.datastore.kudu.config.KuduOptions`]
| Redis           | {store-redis}/datastore/redis/config/RedisOptions.java[`org.locationtech.geowave.datastore.redis.config.RedisOptions`]
| RocksDB         | {store-rocksdb}/datastore/rocksdb/config/RocksDBOptions.java[`org.locationtech.geowave.datastore.rocksdb.config.RocksDBOptions`]
|======================

Once the options class has been initialized with all of the desired options, a {core-store}/core/store/api/DataStore.java[`DataStore`] can be created using the {core-store}/core/store/api/DataStoreFactory.java[`DataStoreFactory`].  The following example shows how to create a RocksDB data store:

[source, java]
----
RocksDBOptions options = new RocksDBOptions();
options.setDirectory("/myStore");
options.setGeoWaveNamespace("gwNamespace");
DataStore myStore = DataStoreFactory.createDataStore(options);
----

=== Creating Indices

Spatial and spatial-temporal indices are created by using the appropriate index builder. For spatial indices, the {core-geotime}/core/geotime/index/api/SpatialIndexBuilder.java[`SpatialIndexBuilder`] can be used, and for spatial-temporal indices, the {core-geotime}/core/geotime/index/api/SpatialTemporalIndexBuilder.java[`SpatialTemporalIndexBuilder`] can be used. Each builder has options that are specific to the type of index being created.  Once all options have been set, the index can be created with the `createIndex` function.

[source, java]
----
// Spatial Index
SpatialIndexBuilder spatialIndexBuilder = new SpatialIndexBuilder();
spatialIndexBuilder.setCrs("EPSG:4326");
Index spatialIndex = spatialIndexBuilder.createIndex();

// Spatial-temporal Index
SpatialTemporalIndexBuilder spatialTemporalIndexBuilder = new SpatialTemporalIndexBuilder();
spatialTemporalIndexBuilder.setCrs("EPSG:3857");
spatialTemporalIndexBuilder.setPeriodicity(Unit.MONTH);
Index spatialTemporalIndex = spatialTemporalIndexBuilder.createIndex();
----

This index can then be added to the data store with the `addIndex` function.  The following example shows how to add these indices to the RocksDB data store created in the previous section:

[source, java]
----
// Add the spatial and spatial-temporal indices
myStore.addIndex(spatialIndex);
myStore.addIndex(spatialTemporalIndex);
----

=== Ingesting Data

Data can be ingested into GeoWave by adding a type to a set of indices and then using the {core-store}/core/store/api/Writer.java[`Writer`] interface to write data.  The following example creates a {adapter-vector}/adapter/vector/FeatureDataAdapter.java[`FeatureDataAdapter`] from a GeoTools `SimpleFeatureType`, adds it to the data store in the spatial index that was created in the previous section, and then uses the {core-store}/core/store/api/Writer.java[`Writer`] to write some features:

[source, java]
----
// Create a point feature type
SimpleFeatureTypeBuilder pointTypeBuilder = new SimpleFeatureTypeBuilder();
AttributeTypeBuilder attributeBuilder = new AttributeTypeBuilder();
pointTypeBuilder.setName("TestPointType");
pointTypeBuilder.add(attributeBuilder.binding(Point.class).nillable(false).buildDescriptor("the_geom"));
pointTypeBuilder.add(attributeBuilder.binding(Date.class).nillable(false).buildDescriptor("date"));
SimpleFeatureType pointType = pointTypeBuilder.buildFeatureType();

// Create a feature builder
SimpleFeatureBuilder pointFeatureBuilder = new SimpleFeatureBuilder(pointType);

// Create an adapter for point type
FeatureDataAdapter pointTypeAdapter = new FeatureDataAdapter(pointType);

// Add the point type to the data store in the spatial index
myStore.addType(pointTypeAdapter, spatialIndex);

// Create a writer to ingest data
try(Writer<SimpleFeature> writer = myStore.createWriter(pointTypeAdapter.getTypeName())) {
  // Write some features to the data store
  GeometryFactory factory = new GeometryFactory();
  pointFeatureBuilder.set("the_geom", factory.createPoint(new Coordinate(1, 1)));
  pointFeatureBuilder.set("date", new Date());
  writer.write(pointFeatureBuilder.buildFeature("feature1"));

  pointFeatureBuilder.set("the_geom", factory.createPoint(new Coordinate(5, 5)));
  pointFeatureBuilder.set("date", new Date());
  writer.write(pointFeatureBuilder.buildFeature("feature2"));

  pointFeatureBuilder.set("the_geom", factory.createPoint(new Coordinate(-5, -5)));
  pointFeatureBuilder.set("date", new Date());
  writer.write(pointFeatureBuilder.buildFeature("feature3"));
}
----

=== Querying Data

Data in GeoWave can be queried by using the appropriate {core-store}/core/store/api/QueryBuilder.java[`QueryBuilder`] implementation as described in the <<045-query#query-builders, query builder documentation>>.  The following is an example of using the {core-geotime}/core/geotime/store/query/api/VectorQueryBuilder.java[`VectorQueryBuilder`] to query feature data that lies within a specific bounding box:

[source, java]
----
// Create the query builder and constraints factory
VectorQueryBuilder queryBuilder = VectorQueryBuilder.newBuilder();
VectorQueryConstraintsFactory constraintsFactory = queryBuilder.constraintsFactory();

// Use the constraints factory to create a bounding box constraint
queryBuilder.constraints(constraintsFactory.cqlConstraints("BBOX(the_geom, -1, -1, 6, 6)"));
    
// Only query data from the point type
queryBuilder.addTypeName(pointTypeAdapter.getTypeName());

// Build the query
Query<SimpleFeature> query = queryBuilder.build();

// Execute the query
try (CloseableIterator<SimpleFeature> features = myStore.query(query)) {
  // Iterate through the results
  while(features.hasNext()) {
    SimpleFeature feature = features.next();
    // Do something with the feature
  }
}
----

=== Aggregating Data

Aggregation queries can be performed by using an {core-store}/core/store/api/AggregationQueryBuilder.java[`AggregationQueryBuilder`] as described in the <<045-query#query-builders, query builder documentation>>.  The following is an example of performing a count aggregation on a vector type in the data store for features that lie in a given bounding box:

[source, java]
----
// Create the aggregation query builder
VectorAggregationQueryBuilder<Persistable, Object> aggregationQueryBuilder = VectorAggregationQueryBuilder.newBuilder();

// Use the constraints factory from the previous example to create a bounding box constraint
aggregationQueryBuilder.constraints(constraintsFactory.cqlConstraints("BBOX(the_geom, -1, -1, 6, 6)"));

// Configure the query to use a count aggregation on the desired type
aggregationQueryBuilder.count(pointTypeAdapter.getTypeName());

// Create the aggregation query
AggregationQuery<Persistable, Object, SimpleFeature> aggregationQuery = aggregationQueryBuilder.build();

// Perform the aggregation
Long count = (Long) myStore.aggregate(aggregationQuery);
----

You can also create aggregations for any custom {core-store}/core/store/api/Aggregation.java[`Aggregation`] implementation by using the `aggregate` function of the {core-store}/core/store/api/AggregationQueryBuilder.java[`AggregationQueryBuilder`].

=== Querying Statistics

Statistic queries can be performed by using an appropriate {core-store}/core/store/api/StatisticQueryBuilder.java[`StatisticQueryBuilder`].  The following is an example of querying the bounding box statistic of a vector type in the data store:

[source, java]
----
// Create the statistic query builder
FieldStatisticQueryBuilder<BoundingBoxValue, Envelope> builder = SpatialTemporalStatisticQueryBuilder.bbox();

// Specify the type name
builder.typeName(pointTypeAdapter.getTypeName());

// Create the bounding box statistics query
StatisticQuery<BoundingBoxValue, Envelope> bboxQuery = builder.build();

// Aggregate the statistic into a single result
BoundingBoxValue bboxStatValue = myStore.aggregateStatistics(bboxQuery);

// Get the value
Envelope bbox = bboxStatValue.getValue();
----

NOTE: Specifying the type name in the statistics query is optional and serves to filter statistics to the type we are interested in.  If the type name is not supplied, bounding box statistics for all types will be aggregated.

