/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package mil.nga.giat.geowave.adapter.vector.avro;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class AvroSimpleFeatureCollection extends
		org.apache.avro.specific.SpecificRecordBase implements
		org.apache.avro.specific.SpecificRecord
{
	public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser()
			.parse("{\"type\":\"record\",\"name\":\"AvroSimpleFeatureCollection\",\"namespace\":\"mil.nga.giat.geowave.adapter.vector.avro\",\"fields\":[{\"name\":\"featureType\",\"type\":{\"type\":\"record\",\"name\":\"FeatureDefinition\",\"fields\":[{\"name\":\"featureTypeName\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"attributeNames\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}},{\"name\":\"attributeTypes\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}},{\"name\":\"attributeDefaultClassifications\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}}]}},{\"name\":\"simpleFeatureCollection\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"AttributeValues\",\"fields\":[{\"name\":\"fid\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"values\",\"type\":{\"type\":\"array\",\"items\":\"bytes\"}},{\"name\":\"classifications\",\"type\":[\"null\",{\"type\":\"array\",\"items\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}]}}}]}");

	public static org.apache.avro.Schema getClassSchema() {
		return SCHEMA$;
	}

	@Deprecated
	public mil.nga.giat.geowave.adapter.vector.avro.FeatureDefinition featureType;
	@Deprecated
	public java.util.List<mil.nga.giat.geowave.adapter.vector.avro.AttributeValues> simpleFeatureCollection;

	/**
	 * Default constructor. Note that this does not initialize fields to their
	 * default values from the schema. If that is desired then one should use
	 * <code>newBuilder()</code>.
	 */
	public AvroSimpleFeatureCollection() {}

	/**
	 * All-args constructor.
	 */
	public AvroSimpleFeatureCollection(
			mil.nga.giat.geowave.adapter.vector.avro.FeatureDefinition featureType,
			java.util.List<mil.nga.giat.geowave.adapter.vector.avro.AttributeValues> simpleFeatureCollection ) {
		this.featureType = featureType;
		this.simpleFeatureCollection = simpleFeatureCollection;
	}

	public org.apache.avro.Schema getSchema() {
		return SCHEMA$;
	}

	// Used by DatumWriter. Applications should not call.
	public java.lang.Object get(
			int field$ ) {
		switch (field$) {
			case 0:
				return featureType;
			case 1:
				return simpleFeatureCollection;
			default:
				throw new org.apache.avro.AvroRuntimeException(
						"Bad index");
		}
	}

	// Used by DatumReader. Applications should not call.
	@SuppressWarnings(value = "unchecked")
	public void put(
			int field$,
			java.lang.Object value$ ) {
		switch (field$) {
			case 0:
				featureType = (mil.nga.giat.geowave.adapter.vector.avro.FeatureDefinition) value$;
				break;
			case 1:
				simpleFeatureCollection = (java.util.List<mil.nga.giat.geowave.adapter.vector.avro.AttributeValues>) value$;
				break;
			default:
				throw new org.apache.avro.AvroRuntimeException(
						"Bad index");
		}
	}

	/**
	 * Gets the value of the 'featureType' field.
	 */
	public mil.nga.giat.geowave.adapter.vector.avro.FeatureDefinition getFeatureType() {
		return featureType;
	}

	/**
	 * Sets the value of the 'featureType' field.
	 * 
	 * @param value
	 *            the value to set.
	 */
	public void setFeatureType(
			mil.nga.giat.geowave.adapter.vector.avro.FeatureDefinition value ) {
		this.featureType = value;
	}

	/**
	 * Gets the value of the 'simpleFeatureCollection' field.
	 */
	public java.util.List<mil.nga.giat.geowave.adapter.vector.avro.AttributeValues> getSimpleFeatureCollection() {
		return simpleFeatureCollection;
	}

	/**
	 * Sets the value of the 'simpleFeatureCollection' field.
	 * 
	 * @param value
	 *            the value to set.
	 */
	public void setSimpleFeatureCollection(
			java.util.List<mil.nga.giat.geowave.adapter.vector.avro.AttributeValues> value ) {
		this.simpleFeatureCollection = value;
	}

	/** Creates a new AvroSimpleFeatureCollection RecordBuilder */
	public static mil.nga.giat.geowave.adapter.vector.avro.AvroSimpleFeatureCollection.Builder newBuilder() {
		return new mil.nga.giat.geowave.adapter.vector.avro.AvroSimpleFeatureCollection.Builder();
	}

	/**
	 * Creates a new AvroSimpleFeatureCollection RecordBuilder by copying an
	 * existing Builder
	 */
	public static mil.nga.giat.geowave.adapter.vector.avro.AvroSimpleFeatureCollection.Builder newBuilder(
			mil.nga.giat.geowave.adapter.vector.avro.AvroSimpleFeatureCollection.Builder other ) {
		return new mil.nga.giat.geowave.adapter.vector.avro.AvroSimpleFeatureCollection.Builder(
				other);
	}

	/**
	 * Creates a new AvroSimpleFeatureCollection RecordBuilder by copying an
	 * existing AvroSimpleFeatureCollection instance
	 */
	public static mil.nga.giat.geowave.adapter.vector.avro.AvroSimpleFeatureCollection.Builder newBuilder(
			mil.nga.giat.geowave.adapter.vector.avro.AvroSimpleFeatureCollection other ) {
		return new mil.nga.giat.geowave.adapter.vector.avro.AvroSimpleFeatureCollection.Builder(
				other);
	}

	/**
	 * RecordBuilder for AvroSimpleFeatureCollection instances.
	 */
	public static class Builder extends
			org.apache.avro.specific.SpecificRecordBuilderBase<AvroSimpleFeatureCollection> implements
			org.apache.avro.data.RecordBuilder<AvroSimpleFeatureCollection>
	{

		private mil.nga.giat.geowave.adapter.vector.avro.FeatureDefinition featureType;
		private java.util.List<mil.nga.giat.geowave.adapter.vector.avro.AttributeValues> simpleFeatureCollection;

		/** Creates a new Builder */
		private Builder() {
			super(
					mil.nga.giat.geowave.adapter.vector.avro.AvroSimpleFeatureCollection.SCHEMA$);
		}

		/** Creates a Builder by copying an existing Builder */
		private Builder(
				mil.nga.giat.geowave.adapter.vector.avro.AvroSimpleFeatureCollection.Builder other ) {
			super(
					other);
			if (isValidValue(
					fields()[0],
					other.featureType)) {
				this.featureType = data().deepCopy(
						fields()[0].schema(),
						other.featureType);
				fieldSetFlags()[0] = true;
			}
			if (isValidValue(
					fields()[1],
					other.simpleFeatureCollection)) {
				this.simpleFeatureCollection = data().deepCopy(
						fields()[1].schema(),
						other.simpleFeatureCollection);
				fieldSetFlags()[1] = true;
			}
		}

		/**
		 * Creates a Builder by copying an existing AvroSimpleFeatureCollection
		 * instance
		 */
		private Builder(
				mil.nga.giat.geowave.adapter.vector.avro.AvroSimpleFeatureCollection other ) {
			super(
					mil.nga.giat.geowave.adapter.vector.avro.AvroSimpleFeatureCollection.SCHEMA$);
			if (isValidValue(
					fields()[0],
					other.featureType)) {
				this.featureType = data().deepCopy(
						fields()[0].schema(),
						other.featureType);
				fieldSetFlags()[0] = true;
			}
			if (isValidValue(
					fields()[1],
					other.simpleFeatureCollection)) {
				this.simpleFeatureCollection = data().deepCopy(
						fields()[1].schema(),
						other.simpleFeatureCollection);
				fieldSetFlags()[1] = true;
			}
		}

		/** Gets the value of the 'featureType' field */
		public mil.nga.giat.geowave.adapter.vector.avro.FeatureDefinition getFeatureType() {
			return featureType;
		}

		/** Sets the value of the 'featureType' field */
		public mil.nga.giat.geowave.adapter.vector.avro.AvroSimpleFeatureCollection.Builder setFeatureType(
				mil.nga.giat.geowave.adapter.vector.avro.FeatureDefinition value ) {
			validate(
					fields()[0],
					value);
			this.featureType = value;
			fieldSetFlags()[0] = true;
			return this;
		}

		/** Checks whether the 'featureType' field has been set */
		public boolean hasFeatureType() {
			return fieldSetFlags()[0];
		}

		/** Clears the value of the 'featureType' field */
		public mil.nga.giat.geowave.adapter.vector.avro.AvroSimpleFeatureCollection.Builder clearFeatureType() {
			featureType = null;
			fieldSetFlags()[0] = false;
			return this;
		}

		/** Gets the value of the 'simpleFeatureCollection' field */
		public java.util.List<mil.nga.giat.geowave.adapter.vector.avro.AttributeValues> getSimpleFeatureCollection() {
			return simpleFeatureCollection;
		}

		/** Sets the value of the 'simpleFeatureCollection' field */
		public mil.nga.giat.geowave.adapter.vector.avro.AvroSimpleFeatureCollection.Builder setSimpleFeatureCollection(
				java.util.List<mil.nga.giat.geowave.adapter.vector.avro.AttributeValues> value ) {
			validate(
					fields()[1],
					value);
			this.simpleFeatureCollection = value;
			fieldSetFlags()[1] = true;
			return this;
		}

		/** Checks whether the 'simpleFeatureCollection' field has been set */
		public boolean hasSimpleFeatureCollection() {
			return fieldSetFlags()[1];
		}

		/** Clears the value of the 'simpleFeatureCollection' field */
		public mil.nga.giat.geowave.adapter.vector.avro.AvroSimpleFeatureCollection.Builder clearSimpleFeatureCollection() {
			simpleFeatureCollection = null;
			fieldSetFlags()[1] = false;
			return this;
		}

		@Override
		public AvroSimpleFeatureCollection build() {
			try {
				AvroSimpleFeatureCollection record = new AvroSimpleFeatureCollection();
				record.featureType = fieldSetFlags()[0] ? this.featureType
						: (mil.nga.giat.geowave.adapter.vector.avro.FeatureDefinition) defaultValue(fields()[0]);
				record.simpleFeatureCollection = fieldSetFlags()[1] ? this.simpleFeatureCollection
						: (java.util.List<mil.nga.giat.geowave.adapter.vector.avro.AttributeValues>) defaultValue(fields()[1]);
				return record;
			}
			catch (Exception e) {
				throw new org.apache.avro.AvroRuntimeException(
						e);
			}
		}
	}
}
