== Vector Demo

In the Vector Demo, we use GeoWave to ingest and runs a Kernel Density Estimation on a large set of media/broadcast data provided by the GDELT Project.

=== Set-Up Environment Variables

Download the GeoWave environment script. We will also download two .sld files to use later on in the guide.

[source, bash]
----
cd /mnt
sudo wget s3.amazonaws.com/geowave/latest/scripts/sandbox/quickstart/geowave-env.sh
sudo wget s3.amazonaws.com/geowave/latest/scripts/emr/quickstart/KDEColorMap.sld
sudo wget s3.amazonaws.com/geowave/latest/scripts/emr/quickstart/SubsamplePoints.sld
----  

This script defines a number of the variables that will be used in future commands, so we will source it here.

[source, bash]
----
source /mnt/geowave-env.sh
----

=== Download GDELT Data

We will be using data from the GDELT Project in this guide. For more information about the 
GDELT Project please visit their website http://www.gdeltproject.org/[here]. 

Download whatever gdelt data matches $TIME_REGEX. The example is set to 201602 by sourcing the geowave-env.sh script. **Please make sure that you 
have sourced the environment script before calling this command.**

[source, bash]
----
sudo mkdir $STAGING_DIR/gdelt;cd $STAGING_DIR/gdelt
sudo wget http://data.gdeltproject.org/events/md5sums
for file in `cat md5sums | cut -d' ' -f3 | grep "^${TIME_REGEX}"` ; \ 
do sudo wget http://data.gdeltproject.org/events/$file ; done
md5sum -c md5sums 2>&1 | grep "^${TIME_REGEX}"
cd $STAGING_DIR
----

After the data has been downloaded, we are ready to set up the store and index used to ingest the data.

=== Config and Ingest

Add a GeoWave store.

[source, bash]
----
geowave config addstore gdelt --gwNamespace geowave.gdelt -t hbase --zookeeper sandbox.hortonworks.com:2181
---- 

Add a spatial index.

[source, bash]
----
geowave config addindex -t spatial gdelt-spatial --partitionStrategy round_robin --numPartitions $NUM_PARTITIONS
---- 

Ingest the data into geowave.

[source, bash]
----
geowave ingest localtogw /mnt/gdelt gdelt gdelt-spatial -f gdelt --gdelt.cql "INTERSECTS(geometry,$GERMANY)"

---- 

The ingest should take about ~3 minutes. Once the Ingest has started, you can monitor HBase status at the <<150-hw-quickstart-guide-interact.adoc#hbase-master-view, HBase web interface>>. The ingest is complete when your terminal will 
accept user input.

=== Kernel Density Estimation (KDE)

Once the ingest has completed, add another store for the kde.

[source, bash]
----
geowave config addstore gdelt-kde --gwNamespace geowave.kde_gdelt \
-t hbase --zookeeper $HOSTNAME:2181
----

Run the KDE analytic

[source, bash]
----
hadoop jar /usr/local/geowave-0.9.5-hdp2/tools/geowave-tools-0.9.5-hdp2.jar analytic kde --featureType gdeltevent --minLevel 5 --maxLevel 26 --minSplits $NUM_PARTITIONS --maxSplits $NUM_PARTITIONS --coverageName gdeltevent_kde --hdfsHostPort sandbox.hortonworks.com:${HDFS_PORT} --jobSubmissionHostPort sandbox.hortonworks.com:${RESOURCE_MAN_PORT} --tileSize 1 gdelt gdelt-kde
----

The KDE can take 5-10 minutes to complete due to the size of the dataset. Once it starts, its progress will be displayed in the terminal, and HBase status can be monitored at the <<150-hw-quickstart-guide-interact.adoc#hbase-master-view, HBase web interface>>.

Once the KDE has run its course successfully, you should be able to view the heatmap generated by it, as well as a map of all of the ingested data points. If you would like to do this before completing the Raster Demo, proceed to <<145-hw-quickstart-guide-geoserver.adoc#integrate-with-geoserver-2, Integrate with Geoserver>>
and then to the <<150-hw-quickstart-guide-interact.adoc#interacting-with-the-cluster-2, Interacting with the Cluster>> section. You will still be able to view the results for both demos after completing the Raster Demo.


