<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<artifactId>geowave-parent</artifactId>
		<groupId>org.locationtech.geowave</groupId>
		<relativePath>../</relativePath>
		<version>3.0.0-SNAPSHOT</version>
	</parent>
	<artifactId>geowave-deploy</artifactId>
	<name>GeoWave Deployment Configurations</name>
	<properties>
		<tools.finalName>${project.artifactId}-${project.version}-tools</tools.finalName>
		<hbase.finalName>${project.artifactId}-${project.version}-hbase</hbase.finalName>
		<accumulo.finalName>${project.artifactId}-${project.version}-accumulo</accumulo.finalName>
		<geotools.finalName>${project.artifactId}-${project.version}-geoserver</geotools.finalName>
		<maven.build.timestamp.format>yyyy-MM-dd'T'HH:mm:ssZ</maven.build.timestamp.format>
		<build.timestamp>${maven.build.timestamp}</build.timestamp>
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.locationtech.geowave</groupId>
			<artifactId>geowave-adapter-vector</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>org.locationtech.geowave</groupId>
			<artifactId>geowave-adapter-raster</artifactId>
			<version>${project.version}</version>
		</dependency>
	</dependencies>
	<build>
		<resources>
			<resource>
				<filtering>true</filtering>
				<directory>src/main/resources</directory>
				<includes>
					<include>build.properties</include>
					<include>GeoWaveLabels.properties</include>
					<include>log4j2.properties</include>
				</includes>
			</resource>
		</resources>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-resources-plugin</artifactId>
				<version>2.7</version>
				<configuration>
					<encoding>UTF-8</encoding>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>buildnumber-maven-plugin</artifactId>
				<version>1.3</version>
				<executions>
					<execution>
						<phase>validate</phase>
						<goals>
							<goal>create</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
		<pluginManagement>
			<plugins>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-shade-plugin</artifactId>
					<dependencies>
						<dependency>
							<groupId>org.apache.logging.log4j</groupId>
							<artifactId>log4j-transform-maven-shade-plugin-extensions</artifactId>
							<version>0.2.0</version>
						</dependency>
					</dependencies>
				</plugin>
			</plugins>
		</pluginManagement>
	</build>

	<profiles>
		<profile>
			<id>geowave-tools-singlejar</id>
			<dependencies>
				<dependency>
					<groupId>org.locationtech.geowave</groupId>
					<artifactId>geowave-analytic-spark</artifactId>
					<version>${project.version}</version>
				</dependency>
				<dependency>
					<groupId>org.locationtech.geowave</groupId>
					<artifactId>geowave-analytic-mapreduce</artifactId>
					<version>${project.version}</version>
				</dependency>
				<dependency>
					<groupId>org.locationtech.geowave</groupId>
					<artifactId>geowave-datastore-accumulo</artifactId>
					<version>${project.version}</version>
				</dependency>
				<dependency>
					<groupId>org.locationtech.geowave</groupId>
					<artifactId>geowave-datastore-hbase</artifactId>
					<version>${project.version}</version>
				</dependency>
				<dependency>
					<groupId>org.locationtech.geowave</groupId>
					<artifactId>geowave-datastore-cassandra</artifactId>
					<version>${project.version}</version>
				</dependency>
				<dependency>
					<groupId>org.locationtech.geowave</groupId>
					<artifactId>geowave-datastore-dynamodb</artifactId>
					<version>${project.version}</version>
				</dependency>
				<dependency>
					<groupId>org.locationtech.geowave</groupId>
					<artifactId>geowave-datastore-redis</artifactId>
					<version>${project.version}</version>
				</dependency>
				<dependency>
					<groupId>org.locationtech.geowave</groupId>
					<artifactId>geowave-datastore-rocksdb</artifactId>
					<version>${project.version}</version>
				</dependency>
				<dependency>
					<groupId>org.locationtech.geowave</groupId>
					<artifactId>geowave-datastore-filesystem</artifactId>
					<version>${project.version}</version>
				</dependency>
				<dependency>
					<groupId>org.locationtech.geowave</groupId>
					<artifactId>geowave-cli-geoserver</artifactId>
					<version>${project.version}</version>
				</dependency>
				<dependency>
					<groupId>org.locationtech.geowave</groupId>
					<artifactId>geowave-cli-geoserver-embed</artifactId>
					<version>${project.version}</version>
				</dependency>
				<dependency>
					<groupId>org.locationtech.geowave</groupId>
					<artifactId>geowave-format-4676</artifactId>
					<version>${project.version}</version>
				</dependency>
				<dependency>
					<groupId>org.locationtech.geowave</groupId>
					<artifactId>geowave-format-avro</artifactId>
					<version>${project.version}</version>
				</dependency>
				<dependency>
					<groupId>org.locationtech.geowave</groupId>
					<artifactId>geowave-format-gdelt</artifactId>
					<version>${project.version}</version>
				</dependency>
				<dependency>
					<groupId>org.locationtech.geowave</groupId>
					<artifactId>geowave-format-geolife</artifactId>
					<version>${project.version}</version>
				</dependency>
				<dependency>
					<groupId>org.locationtech.geowave</groupId>
					<artifactId>geowave-format-gpx</artifactId>
					<version>${project.version}</version>
				</dependency>
				<dependency>
					<groupId>org.locationtech.geowave</groupId>
					<artifactId>geowave-format-raster</artifactId>
					<version>${project.version}</version>
				</dependency>
				<dependency>
					<groupId>org.locationtech.geowave</groupId>
					<artifactId>geowave-format-tdrive</artifactId>
					<version>${project.version}</version>
				</dependency>
				<dependency>
					<groupId>org.locationtech.geowave</groupId>
					<artifactId>geowave-format-twitter</artifactId>
					<version>${project.version}</version>
				</dependency>
				<dependency>
					<groupId>org.locationtech.geowave</groupId>
					<artifactId>geowave-format-vector</artifactId>
					<version>${project.version}</version>
				</dependency>
				<dependency>
					<groupId>org.locationtech.geowave</groupId>
					<artifactId>geowave-grpc-server</artifactId>
					<version>${project.version}</version>
				</dependency>
				<dependency>
					<groupId>org.locationtech.geowave</groupId>
					<artifactId>geowave-python</artifactId>
					<version>${project.version}</version>
				</dependency>
				<dependency>
					<groupId>org.locationtech.geowave</groupId>
					<artifactId>geowave-migration</artifactId>
					<version>${project.version}</version>
				</dependency>
			</dependencies>
			<build>
				<plugins>
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-shade-plugin</artifactId>
						<version>3.6.2</version>
						<executions>
							<execution>
								<phase>package</phase>
								<goals>
									<goal>shade</goal>
								</goals>
								<configuration>
									<filters>
										<filter>
											<artifact>junit:junit</artifact>
											<includes>
												<include>junit/framework/**</include>
												<include>org/junit/**</include>
											</includes>
											<excludes>
												<exclude>org/junit/experimental/**</exclude>
												<exclude>org/junit/runners/**</exclude>
											</excludes>
										</filter>
										<filter>
											<artifact>*:*</artifact>
											<excludes>
												<exclude>META-INF/*.SF</exclude>
												<exclude>META-INF/*.DSA</exclude>
												<exclude>META-INF/*.RSA</exclude>
											</excludes>
										</filter>
									</filters>
									<transformers>
										<transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
											<manifestEntries>
												<Multi-Release>true</Multi-Release>
												<Main-Class>org.locationtech.geowave.core.cli.GeoWaveMain</Main-Class>
												<Specification-Title>GeoWave</Specification-Title>
												<Specification-Vendor>LocationTech</Specification-Vendor>
												<Specification-Version>${project.version}</Specification-Version>
												<Implementation-Title>org.locationtech.geowave</Implementation-Title>
												<Implementation-Vendor>LocationTech</Implementation-Vendor>
												<Implementation-Version>${project.version}</Implementation-Version>
											</manifestEntries>
										</transformer>
										<transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer" />
										<transformer implementation="org.apache.logging.log4j.maven.plugins.shade.transformer.Log4j2PluginCacheFileTransformer" />
										<!-- merges META-INF/javax.media.jai.registryFile.jai entries instead 
											of overwriting -->
										<transformer implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
											<resource>META-INF/javax.media.jai.registryFile.jai</resource>
										</transformer>
										<!-- merges META-INF/registryFile.jai entries instead of overwriting -->
										<transformer implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
											<resource>META-INF/registryFile.jai</resource>
										</transformer>
										<!-- merges META-INF/registryFile.jaiext entries instead of overwriting -->
										<transformer implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
											<resource>META-INF/registryFile.jaiext</resource>
										</transformer>
									</transformers>
									<createDependencyReducedPom>false</createDependencyReducedPom>
									<minimizeJar>false</minimizeJar>
									<finalName>${tools.finalName}</finalName>
								</configuration>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>
		<profile>
			<id>geotools-container-singlejar</id>
			<properties>
				<geotools.scope>provided</geotools.scope>
				<container.extension>-geotools-container</container.extension>
			</properties>
			<dependencies>
				<dependency>
					<groupId>org.locationtech.geowave</groupId>
					<artifactId>geowave-datastore-accumulo</artifactId>
					<version>${project.version}</version>
				</dependency>
				<dependency>
					<groupId>org.locationtech.geowave</groupId>
					<artifactId>geowave-datastore-hbase</artifactId>
					<version>${project.version}</version>
				</dependency>
				<dependency>
					<groupId>org.locationtech.geowave</groupId>
					<artifactId>geowave-datastore-cassandra</artifactId>
					<version>${project.version}</version>
				</dependency>
				<dependency>
					<groupId>org.locationtech.geowave</groupId>
					<artifactId>geowave-datastore-dynamodb</artifactId>
					<version>${project.version}</version>
				</dependency>
				<dependency>
					<groupId>org.locationtech.geowave</groupId>
					<artifactId>geowave-datastore-redis</artifactId>
					<version>${project.version}</version>
				</dependency>
				<dependency>
					<groupId>org.locationtech.geowave</groupId>
					<artifactId>geowave-datastore-rocksdb</artifactId>
					<version>${project.version}</version>
				</dependency>
				<dependency>
					<groupId>org.locationtech.geowave</groupId>
					<artifactId>geowave-datastore-filesystem</artifactId>
					<version>${project.version}</version>
				</dependency>
				<dependency>
					<!-- This is required in case ImageDataAdapter is needed in the classpath -->
					<groupId>org.locationtech.geowave</groupId>
					<artifactId>geowave-format-4676</artifactId>
					<version>${project.version}</version>
				</dependency>
			</dependencies>
			<build>
				<plugins>
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-shade-plugin</artifactId>
						<version>3.6.2</version>
						<executions>
							<execution>
								<phase>package</phase>
								<goals>
									<goal>shade</goal>
								</goals>
								<configuration>
									<artifactSet>
										<excludes>
											<exclude>org.slf4j:*</exclude>
											<!-- Below are the exclusions copied from src/main/assembly/assembly-geotools-container.xml -->
											<exclude>*:pom:*</exclude>
											<exclude>log4j:log4j</exclude>
											<exclude>commons-codec:commons-codec</exclude>

											<!-- the required version of guava should exist in geoserver's 
												classpath, although in order to get guava's StopWatch working with HBase 
												1.2.x we need no later than guava 16.0 -->
											<exclude>com.google.guava:guava</exclude>
											<!-- even though commons-lang should exist in geoserver's classpath 
												it is version 2.1 which is missing necessary classes, <exclude>*:commons-lang:*</exclude> -->

											<!-- and commons-lang3 is also necessary due to different classes 
												<exclude>org.apache.commons:commons-lang3</exclude> -->
											<exclude>tomcat:*</exclude>
											<exclude>javax.media:jai*:*</exclude>
											<exclude>com.sun.jersey:*</exclude>
											<exclude>*:servlet*:*</exclude>
											<exclude>*:javax.servlet*:*</exclude>
											<exclude>*:jsp*:*</exclude>
											<exclude>*:jetty*:*</exclude>
											<exclude>*:commons-httpclient:*</exclude>
											<exclude>*:maven*:*</exclude>
											<exclude>*:commons-logging:*</exclude>
											<exclude>*:commons-io:*</exclude>
											<exclude>*:jts*:*</exclude>
											<exclude>*:activation:*</exclude>
											<exclude>*:servlet-api:*</exclude>
											<exclude>*:*:jsr305</exclude>
											<exclude>org.springframework.security:*</exclude>
											<exclude>org.springframework:*</exclude>
											<exclude>org.geoserver:*</exclude>
											<exclude>xpp3:xpp3_min</exclude>
											<exclude>xpp3:xpp3</exclude>
											<exclude>org.apache.xmlgraphics:batik-ext</exclude>
											<exclude>commons-beanutils</exclude>
											<exclude>commons-digester</exclude>
											<exclude>commons-collections</exclude>
										</excludes>
									</artifactSet>

									<filters>
										<filter>
											<artifact>*:*</artifact>
											<excludes>
												<exclude>META-INF/*.SF</exclude>
												<exclude>META-INF/*.DSA</exclude>
												<exclude>META-INF/*.RSA</exclude>
												<exclude>log4j.properties</exclude>
											</excludes>
										</filter>
									</filters>
									<transformers>
										<transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
											<manifestEntries>
												<Multi-Release>true</Multi-Release>
												<Specification-Title>GeoWave-Tools</Specification-Title>
												<Specification-Vendor>LocationTech</Specification-Vendor>
												<Specification-Version>${project.version}</Specification-Version>
												<Implementation-Title>org.locationtech.geowave</Implementation-Title>
												<Implementation-Vendor>LocationTech</Implementation-Vendor>
												<Implementation-Version>${project.version}</Implementation-Version>
											</manifestEntries>
										</transformer>
										<transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer" />
										<transformer implementation="org.apache.logging.log4j.maven.plugins.shade.transformer.Log4j2PluginCacheFileTransformer" />
										<!-- merges META-INF/javax.media.jai.registryFile.jai entries instead 
											of overwriting -->
										<transformer implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
											<resource>META-INF/javax.media.jai.registryFile.jai</resource>
										</transformer>
										<!-- merges META-INF/registryFile.jai entries instead of overwriting -->
										<transformer implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
											<resource>META-INF/registryFile.jai</resource>
										</transformer>
										<!-- merges META-INF/registryFile.jaiext entries instead of overwriting -->
										<transformer implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
											<resource>META-INF/registryFile.jaiext</resource>
										</transformer>
									</transformers>
									<createDependencyReducedPom>false</createDependencyReducedPom>
									<minimizeJar>false</minimizeJar>
									<finalName>${geotools.finalName}</finalName>
								</configuration>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>
		<profile>
			<id>accumulo-container-singlejar</id>
			<properties>
				<accumulo.scope>provided</accumulo.scope>
				<container.extension>-accumulo-container</container.extension>
			</properties>
			<dependencies>
				<dependency>
					<groupId>org.locationtech.geowave</groupId>
					<artifactId>geowave-datastore-accumulo</artifactId>
					<version>${project.version}</version>
				</dependency>
			</dependencies>
			<build>
				<plugins>
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-shade-plugin</artifactId>
						<version>3.6.2</version>
						<executions>
							<execution>
								<phase>package</phase>
								<goals>
									<goal>shade</goal>
								</goals>
								<configuration>
									<artifactSet>
										<excludes>
											<exclude>org.slf4j:*</exclude>
										</excludes>
									</artifactSet>
									<filters>
										<filter>
											<artifact>*:*</artifact>
											<excludes>
												<exclude>META-INF/*.SF</exclude>
												<exclude>META-INF/*.DSA</exclude>
												<exclude>META-INF/*.RSA</exclude>
												<exclude>log4j.properties</exclude>
											</excludes>
										</filter>
									</filters>
									<transformers>
										<transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
											<manifestEntries>
												<Multi-Release>true</Multi-Release>
												<Specification-Title>GeoWave-Accumulo</Specification-Title>
												<Specification-Vendor>LocationTech</Specification-Vendor>
												<Specification-Version>${project.version}</Specification-Version>
												<Implementation-Title>org.locationtech.geowave</Implementation-Title>
												<Implementation-Vendor>LocationTech</Implementation-Vendor>
												<Implementation-Version>${project.version}</Implementation-Version>
											</manifestEntries>
										</transformer>
										<transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer" />
										<transformer implementation="org.apache.logging.log4j.maven.plugins.shade.transformer.Log4j2PluginCacheFileTransformer" />

										<!-- merges META-INF/javax.media.jai.registryFile.jai entries instead 
											of overwriting -->
										<transformer implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
											<resource>META-INF/javax.media.jai.registryFile.jai</resource>
										</transformer>
										<!-- merges META-INF/registryFile.jai entries instead of overwriting -->
										<transformer implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
											<resource>META-INF/registryFile.jai</resource>
										</transformer>
										<!-- merges META-INF/registryFile.jaiext entries instead of overwriting -->
										<transformer implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
											<resource>META-INF/registryFile.jaiext</resource>
										</transformer>
									</transformers>
									<createDependencyReducedPom>false</createDependencyReducedPom>
									<minimizeJar>false</minimizeJar>
									<finalName>${accumulo.finalName}</finalName>
								</configuration>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>
		<profile>
			<id>hbase-container-singlejar</id>
			<properties>
				<hbase.scope>provided</hbase.scope>
				<container.extension>-hbase-container</container.extension>
				<guava.version>12.0.1</guava.version>
			</properties>
			<dependencies>
				<dependency>
					<groupId>org.locationtech.geowave</groupId>
					<artifactId>geowave-datastore-hbase-coprocessors</artifactId>
					<version>${project.version}</version>
				</dependency>
			</dependencies>
			<build>
				<plugins>
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-shade-plugin</artifactId>
						<version>3.6.2</version>
						<executions>
							<execution>
								<phase>package</phase>
								<goals>
									<goal>shade</goal>
								</goals>
								<configuration>
									<artifactSet>
										<excludes>
											<exclude>org.slf4j:*</exclude>
											<exclude>com.google.protobuf:*</exclude>
											<exclude>org.apache.hadoop:*</exclude>
										</excludes>
									</artifactSet>
									<filters>
										<filter>
											<artifact>*:*</artifact>
											<excludes>
												<exclude>META-INF/*.SF</exclude>
												<exclude>META-INF/*.DSA</exclude>
												<exclude>META-INF/*.RSA</exclude>
												<exclude>log4j.properties</exclude>
											</excludes>
										</filter>
									</filters>
									<transformers>
										<transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
											<manifestEntries>
												<Multi-Release>true</Multi-Release>
												<Specification-Title>GeoWave-HBase</Specification-Title>
												<Specification-Vendor>LocationTech</Specification-Vendor>
												<Specification-Version>${project.version}</Specification-Version>
												<Implementation-Title>org.locationtech.geowave</Implementation-Title>
												<Implementation-Vendor>LocationTech</Implementation-Vendor>
												<Implementation-Version>${project.version}</Implementation-Version>
											</manifestEntries>
										</transformer>
										<transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer" />
										<transformer implementation="org.apache.logging.log4j.maven.plugins.shade.transformer.Log4j2PluginCacheFileTransformer" />

										<!-- merges META-INF/javax.media.jai.registryFile.jai entries instead 
											of overwriting -->
										<transformer implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
											<resource>META-INF/javax.media.jai.registryFile.jai</resource>
										</transformer>
										<!-- merges META-INF/registryFile.jai entries instead of overwriting -->
										<transformer implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
											<resource>META-INF/registryFile.jai</resource>
										</transformer>
										<!-- merges META-INF/registryFile.jaiext entries instead of overwriting -->
										<transformer implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
											<resource>META-INF/registryFile.jaiext</resource>
										</transformer>
									</transformers>
									<createDependencyReducedPom>false</createDependencyReducedPom>
									<minimizeJar>false</minimizeJar>
									<finalName>${hbase.finalName}</finalName>
								</configuration>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>
</project>
