## This log4j 2.x configuration file for geowave
appender.rolling.type = RollingFile
appender.rolling.name = RollingFile
appender.rolling.fileName =  ${sys:geowave.home:-${sys:user.home}/geowave}/logs/geowave.log
appender.rolling.filePattern =  ${sys:geowave.home:-${sys:user.home}/geowave}/logs/geowave-%i.log.gz
appender.rolling.filePermissions = rw-rw-rw-
appender.rolling.layout.type = PatternLayout
appender.rolling.layout.pattern = %d{dd MMM HH:mm:ss} %p [%c{2}] - %m%n
appender.rolling.policies.type = Policies
appender.rolling.policies.size.type = SizeBasedTriggeringPolicy
appender.rolling.policies.size.size=10MB

rootLogger=WARN, RollingFile

# Loggers set to WARN still matter: --debug raises only the root logger to DEBUG
logger.geotools.name = org.geotools
logger.geotools.level = WARN
logger.geotoolsFactory.name = org.geotools.factory
logger.geotoolsFactory.level = WARN

logger.geoserver.name = org.geoserver
logger.geoserver.level = INFO
logger.vfnyGeoserver.name = org.vfny.geoserver
logger.vfnyGeoserver.level = INFO
logger.vfnyMultipleDefinitionsFactory.name = org.vfny.geoserver.config.web.tiles.definition.MultipleDefinitionsFactory
logger.vfnyMultipleDefinitionsFactory.level = WARN
logger.vfnyGeoserverGlobal.name = org.vfny.geoserver.global
logger.vfnyGeoserverGlobal.level = WARN

logger.springframework.name = org.springframework
logger.springframework.level = WARN
logger.struts.name = org.apache.struts
logger.struts.level = WARN
logger.sparkShutdownHookManager.name = org.apache.spark.util.ShutdownHookManager
logger.sparkShutdownHookManager.level = OFF
logger.sparkEnv.name = org.apache.spark.SparkEnv
logger.sparkEnv.level = ERROR

logger.mapreduce.name = org.apache.hadoop.mapreduce
logger.mapreduce.level = INFO

logger.thrift.name = org.apache.thrift
logger.thrift.level = ERROR

# <Date> [client.ClientConfiguration] - Found no client.conf in default paths. Using default client configuration values.
logger.accumuloClientConfiguration.name = org.apache.accumulo.core.client.ClientConfiguration
logger.accumuloClientConfiguration.level = ERROR

# Avoiding these warnings WARNING: Extension lookup '****', but ApplicationContext is unset.
# <Date> org.geoserver.platform.GeoServerExtensions checkContext
logger.geoserverPlatform.name = org.geoserver.platform
logger.geoserverPlatform.level = ERROR
