<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<artifactId>geowave-service-parent</artifactId>
		<groupId>org.locationtech.geowave</groupId>
		<relativePath>../../</relativePath>
		<version>3.0.0-SNAPSHOT</version>
	</parent>
	<artifactId>geowave-grpc-protobuf</artifactId>
	<name>GeoWave gRPC Protobuf Library with Proto3</name>
	<dependencies>
		<dependency>
			<groupId>io.grpc</groupId>
			<artifactId>grpc-protobuf</artifactId>
		</dependency>
		<dependency>
			<groupId>io.grpc</groupId>
			<artifactId>grpc-stub</artifactId>
		</dependency>
	</dependencies>
	<build>
		<plugins>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>exec-maven-plugin</artifactId>
				<version>1.6.0</version>
				<executions>
					<execution>
						<phase>generate-sources</phase>
						<goals>
							<goal>java</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<includeProjectDependencies>false</includeProjectDependencies>
					<includePluginDependencies>true</includePluginDependencies>
					<mainClass>org.locationtech.geowave.service.grpc.GeowaveOperationGrpcGenerator</mainClass>
					<arguments>
						<argument>${project.build.directory}/generated-protobuf</argument>
					</arguments>
				</configuration>
				<dependencies>
					<dependency>
						<groupId>org.locationtech.geowave</groupId>
						<artifactId>geowave-grpc-protobuf-generator</artifactId>
						<version>${project.version}</version>
						<type>jar</type>
						<exclusions>
							<exclusion>
								<groupId>org.glassfish</groupId>
								<artifactId>javax.el</artifactId>
							</exclusion>
						</exclusions>
					</dependency>
				</dependencies>
			</plugin>
			<plugin>
				<groupId>io.github.ascopes</groupId>
				<artifactId>protobuf-maven-plugin</artifactId>
				<version>5.1.10</version>
				<executions>
					<execution>
						<goals>
							<goal>generate</goal>
						</goals>
						<configuration>
							<protoc>${protobuf.version}</protoc>
							<sourceDirectories>
								<sourceDirectory>${project.basedir}/src/main/protobuf</sourceDirectory>
								<sourceDirectory>${project.build.directory}/generated-protobuf</sourceDirectory>
							</sourceDirectories>
							<plugins>
								<plugin kind="binary-maven">
									<groupId>io.grpc</groupId>
									<artifactId>protoc-gen-grpc-java</artifactId>
									<version>${grpc.version}</version>
								</plugin>
							</plugins>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
</project>

