<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<artifactId>geowave-extension-parent</artifactId>
		<groupId>org.locationtech.geowave</groupId>
		<relativePath>../../</relativePath>
		<version>3.0.0-SNAPSHOT</version>
	</parent>
	<artifactId>geowave-cli-hbase-embed</artifactId>
	<name>GeoWave Embedded HBase</name>
	<description>GeoWave HBase Commands for Running Embedded HBase Server</description>

	<dependencies>
		<dependency>
			<groupId>org.locationtech.geowave</groupId>
			<artifactId>geowave-datastore-hbase</artifactId>
			<version>${project.version}</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.apache.hbase</groupId>
			<artifactId>hbase-testing-util</artifactId>
			<exclusions>
				<exclusion>
					<groupId>org.apache.hbase</groupId>
					<artifactId>hbase-client</artifactId>
				</exclusion>
				<exclusion>
					<groupId>hsqldb</groupId>
					<artifactId>hsqldb</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.apache.hbase</groupId>
			<artifactId>hbase-protocol</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.apache.hadoop</groupId>
			<artifactId>hadoop-minikdc</artifactId>
			<exclusions>
				<exclusion>
					<groupId>org.apache.directory.server</groupId>
					<artifactId>apacheds-protocol-ldap</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.apache.directory.server</groupId>
					<artifactId>apacheds-jdbm-partition</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.apache.directory.server</groupId>
					<artifactId>apacheds-protocol-shared</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.apache.directory.server</groupId>
					<artifactId>apacheds-core-api</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.apache.directory.server</groupId>
					<artifactId>apacheds-mavibot-partition</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.apache.directory.server</groupId>
					<artifactId>apacheds-protocol-kerberos</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.apache.directory.api</groupId>
					<artifactId>api-all</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.apache.directory.server</groupId>
					<artifactId>
						apacheds-interceptor-kerberos
					</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.apache.directory.server</groupId>
					<artifactId>apacheds-ldif-partition</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
	</dependencies>
</project>
