<<<

:linkattrs:

== Vector Queries

=== Overview

In order to facilitate querying GeoWave data from the CLI, a basic query language is available for vector data.  The idea behind the GeoWave Query Language is to provide a familiar way to easily query, filter, and aggregate vector data from a GeoWave data store.  The query language is similar to SQL, but currently only supports `SELECT` and `DELETE` statements.  These queries can be executed using the link:commands.html#vector-query[`vector query`] command.

....
$ geowave vector query "<query>"
....

NOTE: The examples below use a hypothetical data store called `example` with a type called `countries`. This type contains all of the countries of the world with some additional attributes such as population and year established.

=== SELECT Statement

The `SELECT` statement can be used to fetch data from a GeoWave data store.  It supports column selection, aggregation, CQL filtering, and limiting.

==== Simple Queries

A standard `SELECT` statement has the following syntax:

[source,sql]
----
SELECT <attributes> FROM <storeName>.<typeName>
----

In this syntax, `attributes` can be a comma-delimited list of attributes to select from the type, or `*` to select all of the attributes.  Attributes can also be aliased by using the `AS` operator.

===== Examples

.Selecting all attributes of each country:
[source,sql]
----
SELECT * FROM example.countries
----

.Selecting the `geom`, `population`, and `est` attributes from each country, but renaming `geom` to `geometry` and `est` to `established` for the output:
[source,sql]
----
SELECT geom AS geometry, population, est AS established FROM example.countries
----

==== Aggregation Queries

Aggregations can also be done by using aggregation functions.  Aggregation functions usually take an attribute as an argument, however, some aggregation functions work on the whole row as well, in which case `*` is accepted.

The following table shows the aggregation functions currently available through the query language.

[frame="topbot", width="100%", cols="12%,25%,60%", grid="rows", options="header"]
|=========================================================
|Aggregation Function | Parameters| Description
| COUNT               | Attribute Name or `*` | If an attribute name is supplied, counts the number of non-null values for that attribute.  If `*` is supplied, counts the number of features.
| BBOX                | Geometry Attribute Name or `*` | If a geometry attribute name is supplied, calculates the bounding box of all non-null geometries under that attribute.  If `*` is supplied, calculates the bounding box of features using the default geometry.
| SUM                 | Numeric Attribute Name | Calculates the sum of non-null values for the supplied attribute over the result set.
| MIN                 | Numeric Attribute Name | Finds the minimum value of the supplied attribute over the result set.
| MAX                 | Numeric Attribute Name | Finds the maximum value of the supplied attribute over the result set.
|=========================================================

It's important to note that aggregation queries cannot be mixed with non-aggregated columns. If one of the column selectors has an aggregation function, all of the column selectors need to have an aggregation function.

===== Examples

.Counting the number of countries:
[source,sql]
----
SELECT COUNT(*) FROM example.countries
----

.Calculating the total population of all countries:
[source,sql]
----
SELECT SUM(population) FROM example.countries
----

.Getting the bounding box, minimum population, and maximum population of all countries, using aliases to rename the results:
[source,sql]
----
SELECT BBOX(*) AS bounds, MIN(population) AS minPop, MAX(population) AS maxPop FROM example.countries
----

==== CQL Filtering

Both simple and aggregation queries support filtering using link:https://docs.geoserver.org/latest/en/user/tutorials/cql/cql_tutorial.html[CQL filters].  This can be done using the following syntax:

[source,sql]
----
SELECT <attributes> FROM <storeName>.<typeName> WHERE CQL(<cqlFilter>)
----

When using a filter with aggregations, only the data that passes the filter will be aggregated.

===== Examples

.Selecting only countries that have a population over 100 million:
[source,sql]
----
SELECT * FROM example.countries WHERE CQL(population>100000000)
----

.Counting the number of countries in which the male population exceeds the female one (this assumes that each feature has an attribute for `malePop` and `femalePop`):
[source,sql]
----
SELECT COUNT(*) FROM example.countries WHERE CQL(malePop>femalePop)
----

.Calculating the total population of countries that intersect a bounding box that covers a region of Europe:
[source,sql]
----
SELECT SUM(population) FROM example.countries WHERE CQL(BBOX(geom, 7, 46, 23, 51))
----

==== Limit

It is often the case where not all of the data that matches the query parameters is necessary, in this case we can add a `LIMIT` to the query to limit the number of results returned. This can be done using the following syntax:

[source,sql]
----
SELECT <attributes> FROM <storeName>.<typeName> [ WHERE CQL(<cqlFilter>) ] LIMIT <count>
----

NOTE: While `LIMIT` can be specified for aggregation queries, it doesn't often make sense and can produce different results based on the underlying data store implementation.

===== Examples

.Getting a single country from the dataset:
[source,sql]
----
SELECT * FROM example.countries LIMIT 1
----

.Getting 5 countries that have a population over 100 million:
[source,sql]
----
SELECT * FROM example.countries WHERE CQL(population>100000000) LIMIT 5
----

=== DELETE Statement

The `DELETE` statement can be used to delete vector data from a GeoWave data store.  It can either delete an entire type, or only data that matches a given CQL filter.  It has the following syntax:

[source,sql]
----
DELETE FROM <storeName>.<typeName> [ WHERE CQL(<cqlFilter>) ]
----

IMPORTANT: When all of the data of a given type is removed, that type is removed from the data store completely.  Additionally, if that data represented the last data in an index, the index will also be removed.

===== Examples

.Removing all countries from the data store:
[source,sql]
----
DELETE FROM example.countries
----

.Removing all countries that have a population less than 100 million:
[source,sql]
----
DELETE FROM example.countries WHERE CQL(population<100000000)
----

=== Output Formats

By default, the link:commands.html#vector-query[`vector query`] command outputs all results to the console in a tabular format, however it is often desirable to feed the results of these queries into a format that is usable by other applications.  Because of this, the link:commands.html#vector-query[`vector query`] command supports several output formats, each of which have their own options.  The output format can be changed by supplying the `-f` option on the query.

The following table shows the currently available output formats.

[frame="topbot", width="100%", cols="12%,25%,60%", grid="rows", options="header"]
|=========================================================
|Format   | Options | Description
| console |         | Paged results are printed to the console.  This is the default output format.
| csv     | `-o` or `--outputFile` | Outputs the results to a CSV file specified by the `-o` option.
| shp     | `-o` or `--outputFile`, `-t` or `--typeName` | Outputs the results to a Shapefile specified by the `-o` option and, if specified, gives it a type name specified by the `-t` option.  If no type name is specified `results` will be used as the type name. *This format requires a geometry attribute to be selected*.
| geojson | `-o` or `--outputFile`, `-t` or `--typeName` | Outputs the results to a GeoJSON file specified by the `-o` option and, if specified, gives it a type name specified by the `-t` option.  If no type name is specified `results` will be used as the type name. *This format requires a geometry attribute to be selected*.
|=========================================================

=== Examples

.Output paged results to console:
....
$ geowave vector query "SELECT * FROM example.countries"
....

.Output aggregation results to console:
....
$ geowave vector query "SELECT BBOX(*) AS bounds, MIN(population) AS minPop, MAX(population) AS maxPop FROM example.countries"
....

.Output country names and populations to a CSV file:
....
$ geowave vector query -f csv -o myfile.csv "SELECT name, population FROM example.countries"
....

.Output countries with a population greater than 100 million to a Shapefile:
....
$ geowave vector query -f shp -o results.shp "SELECT * FROM example.countries WHERE CQL(population>100000000)"
....


