[[toolsframework]]
<<<

:linkattrs:

== Tools Framework
A plugin framework (using Service Provider Interface [SPI] based injection) is provided with several input formats and utilities supported out of the box.

[NOTE]
====
This section assumes that a GeoWave build is available. Building GeoWave from source is outside the scope of this document. For details on generating a GeoWave build, please reference the link:devguide.html#building-code[GeoWave Developer Guide, window="_blank"].
====

=== GeoWave Command Line Instructions
GeoWave comes available with several levels of command-line functionality. In this section, we will provide a high-level overview of the commands and will also outline a few of the core functions available, though for a full exhaustive list of commands, please see the link:commands.html[GeoWave CLI Appendix^, window="_blank"].

[NOTE]
====
It is assumed that a _geowave_ system command alias is registered in the terminal session being run through.

To test this, type 'geowave' (no quotes) and press enter.

If a list of geowave options is returned, then the system command alias is available. Otherwise, if an error similar to or containing the term, __'geowave: command not found'__ is returned, the system command alias has not been registered. For details on how to register the 'geowave' system command alias, please refer to the link:devguide.html#packaging-code[GeoWave Developer Guide, window="_blank"].

If the alias system command is not registered, the full java command - ( e.g., java -cp {GEOWAVE_HOME} {GEOWAVE_JAR} ) - will need to be used in place of the 'geowave' alias.
====

==== General Usage & Options
For root-level command-line usage of GeoWave, run the 'geowave' command.
[source, bash]
----
$ geowave
----
This will return all available commands through GeoWave along with a brief description of each.

.Options:
- --config-file:
+
Override configuration file (default is <home>/.geowave/config.properties).
+
This flag must come after 'geowave' and before any subcommand.
- --debug:
+
Verbose output. Use the debug flag to increase the debug logging output by GeoWave on the console to DEBUG. By default, it is set to WARN.
+
This flag must come after 'geowave' and before any subcommand.
- --version:
+
The version flag will output the build arguments that were used to build GeoWave as well as the version of the GeoWave tools jar you’re using:

[NOTE]
====
Not all three options are required. All have been listed as example, though each can be used independently or as any combination of the three options.
====

Example:
[source, bash]
----
$ geowave --config-file {path to configuration file override} --debug --version
----

==== Accumulo
Utility operations to set accumulo splits
[source, bash]
----
$ geowave accumulo
----

==== Analytic
Commands that run mapreduce or spark processing to enhance an existing GeoWave dataset

[source, bash]
----
$ geowave analytic
----

==== Config
Commands that affect local configuration only

[source, bash]
----
$ geowave config
----

==== Explain
See what arguments are missing and what values will be used for GeoWave commands

[source, bash]
----
$ geowave explain
----

==== GeoServer
Commands that manage geoserver data stores and layers

[source, bash]
----
$ geowave gs
----

==== HBase
Utility operations to combine statistics in hbase

[source, bash]
----
$ geowave hbase
----

==== Help
The help command will show arguments and their defaults. It can be prepended to any GeoWave command. If you use it while also specifying a sub-command and its arguments, that command’s help information will be displayed:

[source, bash]
----
$ geowave help <command> <subcommand>
----

==== Ingest
Commands that ingest data directly into GeoWave or stage data to be ingested into GeoWave

[source, bash]
----
$ geowave ingest
----

==== Landsat
Operations to analyze, download, and ingest Landsat 8 imagery publicly available on AWS

[source, bash]
----
$ geowave landsat
----

==== OSM
Operations to ingest OSM nodes, ways and relations to GeoWave

[source, bash]
----
$ geowave osm
----

==== Raster
Operations to perform transformations on raster data in GeoWave

[source, bash]
----
$ geowave raster
----

==== Remote
Operations to manage a remote store

[source, bash]
----
$ geowave remote
----

==== Vector
Vector data operations

[source, bash]
----
$ geowave vector
----
