[[ingest-new-formats]]
<<<
[[ingest-new-formats]]
=== New Formats

:linkattrs:

There are multiple ways to get data into GeoWave. In other sections, we will discuss higher order frameworks, mapreduce
interfaces, etc. The intent here is "just the basics" - the least framework intensive way that one can load
geospatial data.

Information here will reference the link:https://github.com/locationtech/geowave/blob/master/examples/src/main/java/mil/nga/giat/geowave/examples/ingest/SimpleIngest.java[SimpleIngest, window="_blank"] and link:https://github.com/locationtech/geowave/blob/master/examples/src/main/java/mil/nga/giat/geowave/examples/ingest/SimpleIngestProducerConsumer.java[SimpleIngestProducerConsumer, window="_blank"] examples in the geowave-examples project.

.Supported DataStores:
* <<060-ingest-new-formats.adoc#accumulo-datastore, Accumulo DataStore>>
* <<060-ingest-new-formats.adoc#hbase-datastore, HBase DataStore>>

==== Minimum information needed

GeoWave requires a few pieces of fundamental information in order to persist data, including:

[[accumulo-datastore]]
.Accumulo DataStore
* link:https://github.com/locationtech/geowave/blob/master/extensions/datastores/accumulo/src/main/java/mil/nga/giat/geowave/datastore/accumulo/BasicAccumuloOperations.java[BasicAccumuloOperations, window="_blank"] object
** This class contains the information required to connect to an Accumulo instance and which table to use in Accumulo.
** Zookeepers: In the format zookeeper1:port,zookeeper2:port,etc...
** Accumulo Instance ID: This is the "instance" that the Accumulo cluster you are connecting to was initialized with. It's a global setting per cluster.
** Accumulo Username: this is the name of the user you would like to connect as. This is a user account managed by
accumulo, not a system, etc. user.
** Accumulo Password: This is the password associated with the user specified above. Again, this is an accumulo controlled secret.
** Geowave Namespace: This is _not_ an Accumulo namespace. Think of it as a prefix GeoWave will use on any tables it creates. The only current constraint is only one index type is allowed per namespace.
* SimpleFeatureType instance
** link:http://www.opengeospatial.org/standards/sfs[Simple Feature Types, window="_blank"] are an OGC specification for defining geospatial
features. Leveraging this standard is one of the easiest ways to get GIS data into GeoWave.
** SimpleFeatureType instance: (link:http://docs.geotools.org/stable/javadocs/org/opengis/feature/simple/SimpleFeatureType.html[org.opengis.feature.simple.SimpleFeatureType, window="_blank"]) - this defines the names, types, and other
metadata (nullable, etc) of a feature. Think of it as a map of name:values where the values are typed.
* DataAdapter instance
** A GeoWave data adapter is an implementation of the DataAdapter interface that handles the persistence serialization of whatever the object you are storing.
** We are storing SimpleFeatures, so we can leverage the provided FeatureDataAdapter
* Index instance
** The final piece needed - the index defines which attributes are indexed and how that index is constructed.
* DataStore
** This is the piece that puts everything above together.
** Initialization requires a BasicAccumuloOperations instance. The rest are provided as parameters for calls which need them.

[[hbase-datastore]]
.HBase DataStore
* link:https://github.com/locationtech/geowave/blob/master/extensions/datastores/hbase/src/main/java/mil/nga/giat/geowave/datastore/hbase/operations/BasicHBaseOperations.java[BasicHBaseOperations, window="_blank"] object
** This class contains the information required to connect to an hbase instance - and which table to use in hbase.
** Zookeepers: in the format zookeeper1:port,zookeeper2:port,etc...
** Geowave Namespace: this is _not_ an HBase namespace; rather think of it as a prefix geowave will use on any tables it creates. The only current constraint is only one index type is allowed per namespace.
* SimpleFeatureType instance
** link:http://www.opengeospatial.org/standards/sfs[Simple Feature Types, window="_blank"] are an OGC specification for defining geospatial features. Leveraging this standard is one of the easiest ways to get GIS data into GeoWave
** SimpleFeatureType instance: link:http://docs.geotools.org/stable/javadocs/org/opengis/feature/simple/SimpleFeatureType.html[org.opengis.feature.simple.SimpleFeatureType, window="_blank"] - this defines the names, types, and other metadata (nullable, etc) of a feature. Think of it as a map of name:values where the values are typed.
* DataAdapter instance
** A geowave data adapter is an implementation of the DataAdapter interface that handles the persistence serialization of
whatever the object you are storing.
** We are storing SimpleFeatures, so we can leverage the provided FeatureDataAdapter
* Index instance
** The final piece needed is the index defines which attributes are indexed and how that index is constructed.
* DataStore
** This is the piece that puts everything above together.
** Initialization requires a BasicAccumuloOperations instance. The rest are provided as parameters for calls which need them.


==== Other methods

There are other patterns that can be used. See the various classes in the geowave-examples project. The method displayed above is the suggested pattern. It's demonstrated in link:https://github.com/locationtech/geowave/blob/master/examples/src/main/java/mil/nga/giat/geowave/examples/ingest/SimpleIngestIndexWriter.java[SimpleIngestIndexWriter.java, window="_blank"].

The other methods displayed work, but are either more complicated than necessary (link:https://github.com/locationtech/geowave/blob/master/examples/src/main/java/mil/nga/giat/geowave/examples/ingest/SimpleIngestProducerConsumer.java[SimpleIngestProducerConsumer.java, window="_blank"]) or not very efficient (link:https://github.com/locationtech/geowave/blob/master/examples/src/main/java/mil/nga/giat/geowave/examples/ingest/SimpleIngest.java[SimpleIngest.java, window="_blank"]).
