[[install-from-rpm]]
<<<

:linkattrs:

== Installation from RPM

=== Overview

There is a public link:packages.html[GeoWave RPM Repo, window="_blank"] available with the distribution packages and vendors listed below. As you'll need to coordinate a restart of Accumulo to pick up changes to the GeoWave iterator classes the repos default to be disabled so you can keep auto updates enabled. When ready to do an update, simply add `--enablerepo=geowave` to your command. The packages are built for a number of different hadoop distributions (Cloudera, Hortonworks, and Apache). The RPMs have the vendor name embedded as the second portion of the rpm name (geowave-apache-accumulo, geowave-hdp2-accumulo, geowave-cdh5-accumulo, geowave-apache-hbase, etc.)


=== Examples

Use the GeoWave repo RPM to configure a host and search for GeoWave RPMs to install.

[NOTE]
====
Several of the RPMs (accumulo, hbase, jetty, single-host, and tools) are both GeoWave version and vendor version specific. In the examples, below the rpm name geowave-$VERSION-VENDOR_VERSION should be adjusted as needed.
====

Currently supported distribution vendors through GeoWave include:

[ width="50%" cols="25%,75%", options="header"]
|============
| Distribution Vendor | Vendor Abbreviation
| Apache              | apache
| Cloudera            | cdh5
| Hortonworks         | hdp2
|============

[source, bash]
----
rpm -Uvh http://s3.amazonaws.com/geowave-rpms/release/noarch/geowave-repo-1.0-3.noarch.rpm

# To search for GeoWave packages for a specific distribution
yum --enablerepo=geowave search geowave-$VERSION-$VENDOR-*

# To install a specific GeoWave package on a host (probably a namenode)
yum --enablerepo=geowave install geowave-$VERSION-$VENDOR-$PACKAGE

# Update all packages for a specific venfors distribution
yum --enablerepo=geowave install geowave-$VERSION-$VENDOR-*
----

GeoWave RPMs
[cols="35%,65%", options="header"]
|=================
| Name                                 | Description
| geowave-$VERSION-$VENDOR-accumulo    | Accumulo Components
| geowave-$VERSION-$VENDOR-hbase       | HBase Components
| geowave-$VERSION-core                | Core (home directory and geowave user)
| geowave-$VERSION-docs                | Documentation (HTML, PDF and man pages)
| geowave-$VERSION-$VENDOR-tools       | Command Line Tools (ingest, etc.)
| geowave-$VERSION-$VENDOR-gwtomcat    | GeoServer components installed into /usr/local/geowave/geoserver and available at, e.g., http://localhost:8080/geoserver/web
| geowave-$VERSION-puppet              | Puppet Scripts
| geowave-$VERSION-$VENDOR-single-host | All GeoWave components installed on a single host (sometimes useful for development)
| geowave-repo                         | GeoWave RPM Repo config file
| geowave-repo-dev                     | GeoWave Development RPM Repo config file
|=================

[NOTE]
====
.In the above table, replace the following:
* $VERSION: Version of GeoWave source, e.g., ${project.version}
* $VENDOR:  Distribution vendor abbreviation - from vendors table above, e.g., apache, cdh5, hdp2
* $PACKAGE: Package - see RPMs table above, i.e. accumulo, hbase, jetty, single-host, tools

For all vendors or packages for a particular version, replace with * (e.g., 'geowave-${project.version}-apache-*') for all apache apache packages in ${project.version} version of GeoWave.

Note that only accumulo, hbase, jetty, tools, and single-host are vendor package rpm's. All others are version RPMs.
====

=== RPM Installation Notes

RPM names contain the version in the name so support concurrent installations of multiple GeoWave and/or vendor versions. A versioned /usr/local/geowave-$GEOWAVE_VERSION-$VENDOR_VERSION directory is linked to /usr/local/geowave using alternatives ex: /usr/local/geowave -> /usr/local/geowave-0.9.3-hdp2, but there could also be another /usr/local/geowave-0.9.2.1-cdh5 still installed but not the current default.

==== View geowave-home installed and default using alternatives

[source, bash]
----
alternatives --display geowave-home
geowave-home - status is auto.
 link currently points to /usr/local/geowave-0.9.3-hdp2
/usr/local/geowave-0.9.3-hdp2 - priority 90
/usr/local/geowave-0.9.2.1-cdh5 - priority 89
Current `best' version is /usr/local/geowave-0.9.3-hdp2.
----

.geowave-*-accumulo:
This RPM will install the GeoWave Accumulo iterator into the local file system and then upload it into HDFS using the `hadoop fs -put` command. This means of deployment requires that the RPM is installed on a node that has the correct binaries and configuration in place to push files to HDFS, like your namenode. We also need to set the ownership and permissions correctly within HDFS and as such, need to execute the script as a user that has superuser permissions in HDFS. This user varies by Hadoop distribution vendor. If the Accumulo RPM installation fails, check the install log located at `/usr/local/geowave/accumulo/geowave-to-hdfs.log` for errors. The script can be re-run manually if there was a problem that can be corrected like the HDFS service was not started. If a non-default user was used to install Hadoop you can specify a user that has permissions to upload with the --user argument `/usr/local/geowave/accumulo/deploy-to-geowave-to-hdfs.sh --user my-hadoop-user`

[NOTE]
====
This only applies to the Accumulo RPM. There is no such requirement for the HBase RPM.
====

With the exception of the Accumulo RPM mentioned above, there are no restrictions on where you install RPMs. You can install the rest of the RPMs all on a single node for development use or a mix of nodes depending on your cluster configuration.
