[[building]]
<<<
== Building

GeoWave will shortly be available in maven central (for tagged releases), but until then - or to get the latest
features - building GeoWave from source is the best bet.

=== Application Dependencies

This _ultra_ quickstart assumes you have installed and configured:

* http://git-scm.com/[Git]
* http://www.oracle.com/technetwork/java/javase/downloads/index.html[Java JDK] (>= 1.8). The OracleJDK is the most thoroughly tested, but there
are no known issues with OpenJDK.
* https://maven.apache.org/[Maven] >= 3.2.1
* http://geoserver.org/[GeoServer] instance >= 2.5.2
* https://accumulo.apache.org/[Apache Accumulo] version 1.5 or greater is required. 1.5.0, 1.5.1, and 1.6.0 have all
been tested.
* https://hbase.apache.org/[Apache HBase] >= 1.2.1
* http://hadoop.apache.org/[Apache Hadoop] versions 1.x and 2.x
* http://cloudera.com/content/cloudera/en/home.html[Cloudera] CDH4 and CDH5
* http://hortonworks.com/hdp/[Hortonworks Data Platform] 2.1+
* http://www.oracle.com/technetwork/articles/javaee/jai-142803.html[Java Advanced Imaging] and https://docs.oracle.com/javase/8/docs/technotes/guides/imageio/[Java
Image I/O] are also both required to be installed on the GeoServer instance(s) _as well_ as on the Accumulo nodes. The Accumulo support is
only required for certain functions (distributed rendering) - so this may be skipped in some cases.

=== Maven dependencies

Required repositories not in Maven Central have been added to the parent POM. Specifically the cloudera and opengeo repos.

=== Build Process

Checkout GeoWave, set your preferred dependencies as build arguments and then run maven install.

[source, bash]
----
export BUILD_ARGS="-Daccumulo.version=1.7.2 -Daccumulo.api=1.7 -Dhbase.version=1.3.0 -Dhadoop.version=2.7.3 -Dgeotools.version=16.0 -Dgeoserver.version=2.10.0" <1>
git clone https://github.com/ngageoint/geowave.git <2>
cd geowave
mvn install $BUILD_ARGS <3>
----
<1> Examples of current build args can be seen in the top level .travis.yml file in the env/matrix section
<2> If you don't need the complete history and want to speed up the clone you can limit the depth of your checkout with --depth NUM_COMMITS
<3> You can speed up the build by skipping tests by adding -Dfindbugs.skip=true -Dformatter.skip=true -DskipITs=true -DskipTests=true

[NOTE]
====
Integration Tests: Windows

Integration tests are currently not working on Windows out of the box. If you install cygwin and set the environmental variable CYGPATH to the
location of the cygpath binary provided by cygwin then this should work.
====

=== Docker Build Process

We have support for building both the GeoWave jar artifacts and RPMs from Docker containers. This capability is
useful for a number of different situations:

* Jenkins build workers can run Docker on a variety of host operating systems and build for others
* Anyone running Docker will be able to duplicate our build and packaging environments
* Will allow us to build on existing container clusters instead of single purpose build VMs

If building artifacts using Docker containers interests you check out the README in `deploy/packaging/docker`
