[[jace-jni-proxies]]
<<<

:linkattrs:

== Jace JNI Proxies

Using Jace, we are able to create JNI proxy classes for GeoWave that can be used in C/C++ applications.

Boost is required when using the Jace bindings.

=== Prepackaged Source and Binaries

There is a public link:packages.html[GeoWave RPM Repo, window="_blank"] where you can download a tarball for the GeoWave Jace bindings for your desired platform. If your platform is not available, there is a source tarball which can be used in conjunction with CMake to build the GeoWave Jace bindings for your desired platform.

=== Generate Proxies and Build from Source

If you want, you can generate and build the Jace proxies yourself. For more details on how to do this, please check out the link:devguide.html#proxies[GeoWave Developer Guide, window="_blank"].

=== Mapnik Plugin Configuration

==== Mapnik

link:http://mapnik.org/[Mapnik, window="_blank"] is an open source toolkit for developing mapping applications. GeoWave is supported as a plugin for Mapnik for reading vector data from Accumulo.

=== PDAL Plugin Configuration

==== PDAL

The Point Data Abstraction Library link:http://www.pdal.io/index.html[PDAL, window="_blank"] is a BSD licensed library for translating and manipulating point cloud data of various formats. GeoWave is supported as a plugin for PDAL for both reading and writing data to Accumulo.

Note: These instructions assume that you are using prepackaged binaries.

==== Configure CMake for PDAL

To configure PDAL to run with GeoWave, there are a few CMake options that need to be configured. While some of the options (namely the JAVA options) may configure automatically, some will need to be set manually. Refer to the table below to get an idea for how these options would be configured on Ubuntu 14.04 LTS.

[cols="3*", options="header"]
|===
|Option
|Value
|Automatically Configured?

|BUILD_PLUGIN_GEOWAVE
|ON
|

|BUILD_GEOWAVE_TESTS
|ON
|

|GEOWAVE_RUNTIME_JAR
|/path/to/geowave/geowave-runtime.jar
|

|GEOWAVE_INCLUDE_DIR
|/path/to/geowave/include
|

|GEOWAVE_LIBRARY
|/path/to/geowave/libgeowave.so
|

|JAVA_AWT_INCLUDE_PATH
|/usr/lib/jvm/java-8-oracle/include
|X

|JAVA_INCLUDE_PATH
|/usr/lib/jvm/java-8-oracle/include
|X

|JAVA_INCLUDE_PATH2
|/usr/lib/jvm/java-8-oracle/include/linux
|X

|JAVA_AWT_LIBRARY
|/usr/lib/jvm/java-8-oracle/jre/lib/amd64/libjawt.so
|X

|JAVA_JVM_LIBRARY
|/usr/lib/jvm/java-8-oracle/jre/lib/amd64/server/libjvm.so
|X
|===

Note: As Boost is a PDAL dependency, it should already be included.

==== Build PDAL

Once CMake is configured, you can proceed with your normal PDAL build process.

Last but not least, you should ensure that the libraries specified above are available via _PATH_ or _LD_LIBRARY_PATH_ when building shared libraries.

Within the PDAL documentation, you can see examples of how GeoWave can be used as both a link:http://www.pdal.io/stages/readers.geowave.html[reader, window="_blank"] and link:http://www.pdal.io/stages/writers.geowave.html[writer, window="_blank"].
