[[puppet]]
<<<

:linkattrs:

== Puppet

=== Overview

A GeoWave link:http://puppetlabs.com/[Puppet module^, window="_blank"] has been provided as part of both the tar.gz archive bundle and as an RPM. This module can be used to install the various GeoWave services onto separate nodes in a cluster or all onto a single node for development.

There are a couple of different RPM repo settings that may need setting. As the repo is disabled by default to avoid picking up new Accumulo iterator jars without coordinating a service restart, there is likely some customization required for a particular use case. Class parameters are intended to be overridden to provide extensibility.

=== Options

geowave_version::
The desired version of GeoWave to install, ex: '${project.version}'. We support concurrent installs but only one will be active at a time.

hadoop_vendor_version::
The Hadoop framework vendor and version against which GeoWave was built. Examples would be cdh5 or hdp2. Check the link:packages.html[available packages^, window="_blank"] site for currently supported hadoop distributions.

install_accumulo::
Install the GeoWave Accumulo Iterator on this node and upload it into HDFS. This node must have a working HDFS client.

install_app::
Install the GeoWave ingest utility on this node. This node must have a working HDFS client.

install_app_server::
Install Jetty with Geoserver and GeoWave plugin on this node.

http_port::
The port on which the Tomcat application server will run - defaults to 8080.

repo_base_url::
Used with the optional geowave::repo class to point the local package management system at a source for GeoWave RPMs. The default location is http://s3.amazonaws.com/geowave-rpms/release/noarch/.

repo_enabled::
To pick up an updated Accumulo iterator you'll need to restart the Accumulo service. We don't want to pick up new RPMs with something like a yum-cron job without coordinating a restart so the repo is disabled by default.

repo_refresh_md::
The number of seconds before checking for new RPMs. On a production system the default of every 6 hours should be sufficient, but you can lower this down to 0 for a development system on which you wish to pick up new packages as soon as they are made available.

=== Examples

==== Development
Install everything on a one-node development system. Use the GeoWave Development RPM Repo and force a check for new RPMs with every pull (don't use cached metadata).

[source, ruby]
----
# Dev VM
class { 'geowave::repo':
  repo_enabled    => 1,
  repo_refresh_md => 0,
} ->
class { 'geowave':
  geowave_version       => '${project.version}',
  hadoop_vendor_version => 'apache',
  install_accumulo      => true,
  install_app           => true,
  install_app_server    => true,
}
----

=== Clustered
Run the application server on a different node. Use a locally maintained rpm repo vs. the one available on the Internet and run the app server on an alternate port, so as not to conflict with another service running on that host.

[source, ruby]
----
# Master Node
node 'c1-master' {
  class { 'geowave::repo':
    repo_base_url   => 'http://my-local-rpm-repo/geowave-rpms/dev/noarch/',
    repo_enabled    => 1,
  } ->
  class { 'geowave':
    geowave_version       => '${project.version}',
    hadoop_vendor_version => 'apache',
    install_accumulo      => true,
    install_app           => true,
  }
}

# App server node
node 'c1-app-01' {
  class { 'geowave::repo':
    repo_base_url   => 'http://my-local-rpm-repo/geowave-rpms/dev/noarch/',
    repo_enabled    => 1,
  } ->
  class { 'geowave':
    geowave_version       => '${project.version}',
    hadoop_vendor_version => 'apache',
    install_app_server    => true,
    http_port             => '8888',
  }
}
----

=== Puppet script management

As mentioned in the overview, the scripts are available from within the link:packages.html[GeoWave source tar bundle^, window="_blank"] (Search for gz to filter the list). You could also use the RPM package to install and pick up future updates on your puppet server.

==== Source Archive

Unzip the source archive, locate puppet-scripts.tar.gz, and manage the scripts yourself on your Puppet Server.

==== RPM

There's a bit of a boostrap issue when first configuring the Puppet server to use the GeoWave puppet RPM as yum won't know about the RPM Repo and the GeoWave Repo Puppet class hasn't been installed yet. There is an RPM available that will set up the yum repo config after which you should install geowave-puppet manually and proceed to configure GeoWave on the rest of the cluster using Puppet.

[source, bash]
----
rpm -Uvh http://s3.amazonaws.com/geowave-rpms/release/noarch/geowave-repo-1.0-3.noarch.rpm
yum --enablerepo=geowave install geowave-puppet
----
