<<<

[[accumulo-config]]
=== Configuring Accumulo for GeoWave

[[accumulo-config-overview]]
==== Overview

The two high level tasks to configure Accumulo for use with GeoWave are to:

. Ensure the memory allocations for the master and tablet server processes are adequate.
. Add the GeoWave libraries to the Accumulo classpath. The libraries are rather large, so ensure the Accumulo Master process has at least 512m of heap space and the Tablet Server processes have at least 1g of heap space.

The recommended Accumulo configuration for GeoWave requires several manual configuration steps, but isolates the GeoWave libraries to application specific classpath(s). This reduces the possibility of dependency conflict issues. You should ensure that each namespace containing GeoWave tables is configured to pick up the GeoWave Accumulo JAR on the classpath.

[[accumulo-config-overview-procedure]]
===== Procedure

. Upload the GeoWave Accumulo JAR to HDFS.
. Create a user and namespace.
. Grant the user ownership permissions on all tables created within the application namespace.
. Create an application or data set specific classpath.
. Configure all tables within the namespace to use the application classpath.

The GeoWave Accumulo JAR is built from source as described in the link:devguide.html#accumulo-jar[Developer Guide^, window="_blank"].

[source, bash]
----
hadoop fs -put geowave-deploy-${project.version}-accumulo.jar /${ACCUMULO_ROOT}/lib/
accumulo shell -u root
createuser geowave // <1>
createnamespace geowave
grant NameSpace.CREATE_TABLE -ns geowave -u geowave <2>
config -s general.vfs.context.classpath.geowave=hdfs://${MASTER_FQDN}:8020/${ACCUMULO_ROOT}/lib/[^.].*.jar <3>
config -ns geowave -s table.classpath.context=geowave <4>
exit
----
<1> You'll be prompted for a password.
<2> Ensure the user has ownership of all tables created within the namespace.
<3> Replace `${ACCUMULO_ROOT}` with Accumulo's root path in HDFS, typically `/accumulo` (see `instance.volumes` in `accumulo.properties`).
<4> Link the namespace with the application classpath. Adjust the labels as needed if you've used different user or application names

These manual configuration steps have to be performed before attempting to create GeoWave index tables. After the initial configuration, you may elect to do further user and namespace creation and configuring to provide isolation between groups and data sets.


[[accumulo-config-managing]]
==== Managing

After installing a number of different iterators, you may want to figure out which iterators have been configured.

[source, bash]
----
# Print all configuration and grep for line containing vfs.context configuration and also show the following line
accumulo shell -u root -p ROOT_PWD -e "config -np" | grep -A 1 general.vfs.context.classpath
----

You will get back a listing of context classpath override configurations that map the application or user context you configured to a specific iterator JAR in HDFS.


[[accumulo-config-versioning]]
==== Versioning

It's of critical importance to ensure that the various GeoWave components are all the same version and that your client is of the same version that was used to write the data.

[[accumulo-config-versioning-basic]]
==== Basic

The GeoWave Accumulo JAR contains a `build.properties` file with the GeoWave version (`project.version`) and the commit it was built from (`project.scm.revision`).  Compare these with the GeoWave client you are using.  After replacing the JAR in HDFS, you must restart Accumulo so that VFS downloads the new version.

.Version and commit of a GeoWave Accumulo JAR
[source, bash]
----
unzip -p geowave-deploy-${project.version}-accumulo.jar build.properties | grep -E "project.version|project.scm.revision"
----

[[accumulo-config-versioning-advanced]]
===== Advanced

When GeoWave tables are first accessed on a tablet server, the vfs classpath tells Accumulo where to download the JAR file from HDFS.
The JAR file is copied into the local `/tmp` directory (the default general.vfs.cache.dir setting) and loaded onto the classpath.
If there is ever doubt as to if these versions match, you can use the commands below from a tablet server node to verify the version of
this artifact.

.Commit hash of the JAR in HDFS
[source, bash]
----
hadoop fs -get /${ACCUMULO_ROOT}/lib/geowave-deploy-${project.version}-accumulo.jar hdfs-geowave-accumulo.jar
unzip -p hdfs-geowave-accumulo.jar build.properties | grep scm.revision | sed s/project.scm.revision=//
----

.Compare with the versions downloaded locally
[source, bash]
----
sudo find /tmp -name "*geowave*accumulo*.jar" -exec unzip -p {} build.properties  \; | grep scm.revision | sed s/project.scm.revision=//
----

The find command will probably locate a number of different versions depending on how often you clean out `/tmp`, one per JVM.  The commit hash of the JAR in HDFS should be present on all tablet servers once Accumulo has been restarted.  An error will occur if a tablet server is missing the correct JAR.
