<<<

:linkattrs:

== Visibility Management

[[visibility-overview]]
=== Overview

When data is written to GeoWave, it may contain visibility constraints. By default, the visibility expression attached to each attribute is empty, which means that the data is visible regardless of which authorizations are present. If a visibility expression is set for an entry, only queries that supply the appropriate authorizations will be able to see it.

Visibility can be configured on a type by utilizing one or more of the visibility options during ingest or when adding a new type via the `type add` command.  These options allow the user to specify the visibility of each field individually, or specify a field in their type that defines visibility information.  One complex example of this would be having a type that contains a field with visibility information in JSON format.  Each name/value pair within the JSON structure defines the visibility for the associated attribute. In the following example, the `geometry` attribute is given a visibility `S` and the `eventName` attribute is given a visibility `TS`.  This means that a user with an authorization set of `["S","TS"]` would be able to see both attributes, while a user with only `["S"]` would only be able to see the `geometry` attribute.

[source, json]
----
{ "geometry" : "S", "eventName": "TS" }
----

JSON attributes can be regular expressions matching more than one feature property name. In the example, all attributes except for those that start with `geo` have visibility `TS`.

[source, json]
----
{ "geo.*" : "S", ".*" : "TS" }
----

The order of the name/value pairs must be considered if one rule is more general than another, as shown in the example. The rule `.$$*$$` matches all properties. The more specific rule `geo.$$*$$` must be ordered first.

For more information about other ways to configure visibility for a type, see the link:commands.html#type-add[`type add`] CLI documentation.

=== Visibility Expressions

It is sometimes necessary to provide more complex visibility constraints on a particular attribute, such as allowing two different authorizations to have view permissions.  GeoWave handles this by using visibility expressions.  These expressions support AND and OR operations through the symbols `&` and `|`.  It also supports parentheses for situations where more complex expressions are required.

==== Examples

.Visibility expression that allows both `A` and `B` authorizations to see the data:
....
A|B
....

.Visibility expression that only shows data if both `A` and `B` authorizations are provided:
....
A&B
....

.Visibility expression that shows data if both `A` and `B` are provided, but also if only `C` is provided:
....
(A&B)|C
....

.Visibility expression that shows data if `A` and one of `B` or `C` are provided:
....
A&(B|C)
....

